src/Serilog.Sinks.NLog/Sinks/NLog/NLogSink.cs

Pass all the context properties along to nlog, which can then be included in the [nlog output](https://github.com/NLog/NLog/wiki/EventContext-layout-renderer), e.g. `${event-context:item=somePropertyItem}`.

pass context properties along to nlog

---

src/Serilog.Sinks.SignalR/Serilog.Sinks.SignalR.csproj
src/Serilog.Sinks.SignalR/Serilog.Sinks.SignalR.nuspec
src/Serilog.Sinks.SignalR/app.config
src/Serilog.Sinks.SignalR/packages.config

There's a breaking change in SignalR 2.1.0 which makes code compiled
against 2.0.0 unable to be binding redirected - hence the update (see issue #307)

Updated to SignalR 2.1.0

---

src/Serilog.Sinks.MongoDB/LoggerConfigurationMongoDBExtensions.cs
src/Serilog.Sinks.MongoDB/Serilog.Sinks.MongoDB.csproj
src/Serilog.Sinks.MongoDB/Serilog.Sinks.MongoDB.nuspec
src/Serilog.Sinks.MongoDB/Sinks/MongoDB/MongoDBSink.cs
src/Serilog.Sinks.MongoDB/packages.config

This is the implementation of #364.
It also removes strong naming from the MongoDB sink as MongoDB isn't strongly named any more

Updating the MongoDB sink to work with the MongoDB c# v2 driver preview

---

src/Serilog/Parameters/PropertyValueConverter-net40.cs
src/Serilog/Parameters/PropertyValueConverter.cs

The IDestructuringPolicies are now run before IEnumerable cast -- allowing an opportunity for policies to support IEnumerable values. Added IsValueTypeDictionary function to simplify the lookup for the dictionary conversion code.

Non-breaking improvement for issue #30

---

src/Serilog.Extras.MSOwin/Serilog.Extras.MSOwin.nuspec

Corrects a minor spelling mistake in the description of the MSOwin nuget package.
I probably would have just ignored this since it is minor were it not for the fact this is the description that gets published on nuget.org and appears in package search results.

Corrects a minor spelling mistake in the description of the MSOwin nuget package

---

src/Serilog.Sinks.Loggly/LoggerConfigurationLogglyExtensions.cs
src/Serilog.Sinks.Loggly/Serilog.Sinks.Loggly.csproj
src/Serilog.Sinks.Loggly/Sinks/Loggly/LogglySink.cs

In the current version of loggly-csharp, client.Log returns a Task, so it needs to be awaited or .Wait()ed otherwise the log message will not succeed if the calling thread is aborted quickly.
https://github.com/neutmute/loggly-csharp/commit/e38b247caa5ce7a1a6c43608635fe4e9a82c9dd9

Wait for Loggly client to submit the log event.

---

Serilog.sln
packages/repositories.config
src/Serilog.Extras.Timing/Extras/Timing/CounterMeasure.cs
test/Serilog.Extras.Timing.Tests/CounterMeasureTests.cs
test/Serilog.Extras.Timing.Tests/Properties/AssemblyInfo.cs
test/Serilog.Extras.Timing.Tests/Serilog.Extras.Timing.Tests.csproj
test/Serilog.Extras.Timing.Tests/packages.config

Using Serilog.Extras.Timing to create two counters they both share a value which is incremented together.
Code:
```csharp
var bookCounter = logger.CountOperation("books", "created books", false, LogEventLevel.Debug);
var authorCounter = logger.CountOperation("authors", "created authors", false, LogEventLevel.Debug);
bookCounter.Write();
authorCounter.Increment();
bookCounter.Write();
```
Output:
```
2015-02-09 22:07:56 [Debug] "books" count = 0 created books
2015-02-09 22:08:13 [Debug] "books" count = 1 created books
```
The fix is a one liner removing the static property on CounterMeasure _value
In the second commit I created a test project for Serilog.Extras.Timing with a test covering this case.

Fixes support for using multiple CounterMeasure

---

src/Serilog.Sinks.ElmahIO/Serilog.Sinks.ElmahIO.nuspec

Updated Serilog.Sinks.ElmahIO.nuspec to point to the newest stable package of elmah.io.

Newest elmah.io package

---

src/Serilog.Sinks.ElasticSearch/Sinks/ElasticSearch/ElasticSearchSink.cs
src/Serilog.Sinks.ElasticSearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
test/Serilog.Sinks.Elasticsearch.Tests/IndexDeciderTests.cs
test/Serilog.Sinks.Elasticsearch.Tests/ModifyElasticSearchPayload.cs
test/Serilog.Sinks.Elasticsearch.Tests/Serilog.Sinks.Elasticsearch.Tests.csproj

We needed to provide seperate indexes for each loglevel, in order to be able to retain certain loglevel for a shorter/longer period of time

Added IndexDecider Func to allow for a custom index pr logevent

---

src/Serilog.FullNetFx/Sinks/PeriodicBatching/PeriodicBatchingSink-net40.cs
src/Serilog.FullNetFx/Sinks/PeriodicBatching/PeriodicBatchingSink.cs

Context for this in issue #357 
Not very happy with the name "ComeFromInvalidAppDomainContext" for the method, but couldn't think of a better one!
Also tried to create a unit test, but it's to do so when the AppDomain and unhandled exceptions are at play. Any suggestions for how to do this?

#357 PeriodicBatchingSink now flushes on unhandled exceptions

---

src/Serilog/LoggerConfiguration.cs

In an [earlier change](https://github.com/serilog/serilog/commit/980de25bfa82619ddf77280741b84fdb7eac2fce) we trimmed the default maximum destructuring depth from 10 to 5, to be more defensive around over-serialization. Experience is showing 5 is too shallow; it's easy to hit it with a collection of objects that each have a collection property containing an object with a collection.
Even small trees/linked lists hit 5 before getting off the ground :-)
I think although the sentiment was good, we just traded one trap (big events) for another trap (surprising nulls in serialized data).
I'm still not sure 10 is the right number, if there's such thing as a "right" number, but it seems it was a better default and there's not much data to go on. //cc @serilog/core

Revert the default destructuring depth back to 10

---

test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Settings/AppSettingsTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/app.config

The test was being ignored because it required an App.config present with a key, so I made the changes required for the test to run - I have it running locally in TeamCity and it's passing, so I'd expect it to run fine in your CI... We'll see.

AppSettings: Update the unit test that checks environment variable expansion is supported

---

src/Serilog.FullNetFx/Sinks/DiagnosticTrace/DiagnosticTraceSink.cs

On Azure, there's a an option to log Trace events to a destination set
on Azure Portal (storage tables or files).    Since Serilog was not
including the event type in the trace log, trace messages generated by
Serilog are not being logged.  There's also a minimum logging level
setting in Azure that uses this event type to choose logging messages to
log.
To get this feature working properly, I updated the Trace sink to
include the event type in the Trace message based on the Serilog
LogEventLevel.

Including logging level in Trace logger

---

src/Serilog/Log.cs

This PR is the first part of #479 for Serilog 1.5.
Are you OK with the type parameter and parameter naming?
1. I considered `TPropertyValue` but chose the shorter `T` to align with [`Action<T>`](https://msdn.microsoft.com/en-us/library/018hxwa8(v=vs.110).aspx)/[`Func<T, TResult>`](https://msdn.microsoft.com/en-us/library/bb549151(v=vs.110).aspx).
2. For the index suffix on the type parameter and parameter names, I debated whether to start with `0` or `1` and went with `0` to align with the parameter names of [`String.Format`](https://msdn.microsoft.com/en-us/library/d9t40k6d(v=vs.110).aspx)'s overloads and because the `messageTemplate` supports specifying numeric property names that start at zero.
3. For the overload that just has a single `propertyValue` parameter, I left the index off …

Add Log overloads that help avoid array and boxing allocations

---

src/Serilog.FullNetFx/Sinks/PeriodicBatching/PeriodicBatchingSink-net40.cs
src/Serilog.FullNetFx/Sinks/PeriodicBatching/PeriodicBatchingSink.cs

The Seq sink needs an opportunity to do periodic processing, regardless of whether any events have been emitted (#507). This PR adds `OnEmptyBatch()` to `PeriodicBatchingSink` to enable this to occur on the same timer thread used for batch processing, so that additional dispose/shut-down code isn't required.
I'm not certain whether other sinks can make use of this at present, but the general scenario (_query a remote service for current logging level_) sounds like one that will appear again, especially after #511.

PeriodicBatchingSink hook for processing on ticks even when the batch is empty

---

src/Serilog/LoggerConfigurationFullNetFxExtensions.cs
src/Serilog/Settings/AppSettings/AppSettingsSettings.cs
test/Serilog.Tests/Settings/AppSettingsTests.cs

Add support for multiple sets of AppSettings using custom prefixes (in v2). Resolves #430

Add support for multiple sets of AppSettings using custom prefixes (in v2)

---

src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

Fixes #560 
I could not find the `NullLogger` mentioned in the issue, but I figured the `SilentLogger` was the one to use instead.

use silent logger when creating a logger and there are no sinks in the configuration

---

src/Serilog.FullNetFx/Enrichers/EnvironmentUserNameEnricher.cs
src/Serilog.FullNetFx/LoggerConfigurationFullNetFxExtensions.cs
src/Serilog.FullNetFx/Serilog.FullNetFx.csproj
test/Serilog.Tests/Enrichers/EnvironmentUserNameEnricherTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

This PR adds an enricher that is similar to the `MachineNameEnricher`, except that it adds the name of the current user running the application, including the domain name if available.

Add EnvironmentUserNameEnricher + unit test

---

src/Serilog/Log.cs
test/Serilog.Tests/LogTests.cs
test/Serilog.Tests/Support/DelegateDisposable.cs
test/Serilog.Tests/Support/DisposableLogger.cs

This implements #566. I wrote Unit tests for this, however I was not able to run them. I'm assuming this has to do with the outstanding #557

#566 - Try and set the log source if it's specified

---

src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

Might be the smallest PR I've ever written. Resolves #561.

LoggerConfiguration.CreateLogger() now throws if called more than once

---

src/Serilog/Sinks/PeriodicBatching/PeriodicBatchingSink.cs
src/Serilog/Sinks/PeriodicBatching/PortableTimer.cs

`Task.Wait()` in this instance may cause marshalling back onto the originating synchronisation context, leading to a deadlock. If this successfully resolves the intermittent test failure we should consider moving this change back to 1.5 as well.
See also: http://stackoverflow.com/questions/28305968/use-task-run-in-synchronous-method-to-avoid-deadlock-waiting-on-async-method
CC @merbla @khellang

Attempt to fix intermittent hang during CoreCLR test runs

---

src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/Sinks/PeriodicBatching/PeriodicBatchingSink.cs

Use "R" round-trip specifier when formatting floating-point numbers to JSON. Without this specifier, floating point numbers logged as JSON cannot be parsed using the standard `Double` and `Single` parsing in the framework, and break libraries such as JSON.NET that rely on these.
See: http://www.hanselman.com/blog/WhyYouCantDoubleParseDoubleMaxValueToStringOrSystemOverloadExceptionsWhenUsingDoubleParse.aspx
(Fixes https://github.com/continuousit/seq-releases/issues/358)

Use round-trippable floating point formatting in JSON

---

src/Serilog/Properties/InternalsVisibleTo.cs
src/Serilog/project.json
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Core/SafeAggregateSinkTests.cs
test/Serilog.Tests/Events/LogEventPropertyValueTests.cs
test/Serilog.Tests/LogTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs
test/Serilog.Tests/Sinks/PeriodicBatching/BatchedConnectionStatusTests.cs
test/Serilog.Tests/Sinks/RollingFile/RollingFileSinkTests.cs
test/Serilog.Tests/Sinks/RollingFile/TemplatedPathRollerTests.cs
test/Serilog.Tests/project.json

Excludes tests using internal APIs until we can modify/rewrite them. Need to get this through so that Serilog has only a single binary identity across all targets.
Adds a fixed "AssemblyVersion" of "2.0.0.0" that we can keep constant throughout the 2.x series.
Fixes #589.

Enable strong naming on CoreCLR builds

---

src/Serilog/Parameters/PropertyValueConverter.cs
src/Serilog/Platform/TypeInfo-net40.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs

Adressing #618 
I used some of the code pointed in the defect discussion, added a function to detect anonymous types based on the type name and some tests.
I didn't add a proper test for VB - a real test using a anonymous type coming from a VB library - as this is a bit tedious. This could be done with [Roslyn](https://github.com/dotnet/roslyn) though but I don't think it's worth the hassle.
I nevertheless did test the new dll in a console app written in VB and it works.

Added function to detect anonymous types and appropriate tests

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/SecondaryLoggerSinkTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Support/Some.cs

Found a few rough edges in `WriteTo.Logger()` - fixes:
- When using `WriteTo.Logger(lc => ...)` the sub-logger inherits the level configured on the parent
- Last-in always wins when setting minimum levels even when switching between `LoggingLevelSwitch` and basic level config
- `WriteTo.Logger` no longer ignores the passed-in level switch argument if present (consistent with other sinks)

Less surprising "child logger" level configuration

---

src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
src/Serilog.Sinks.File/Sinks/File/FileSink.cs
src/Serilog.Sinks.RollingFile/RollingFileLoggerConfigurationExtensions.cs
src/Serilog.Sinks.RollingFile/Sinks/RollingFile/RollingFileSink.cs

This is a rough draft implementation to address #650. I open this PR so we have code to discuss; this code is definitely not ready :wink: 
In all honesty, I don't like the boolean parameter too much. Very often boolean parameters are passed around to mean "behave in this way if true, in that way if false"; I think if two behaviours are distinct enough they should have they own classes (```BufferedFileSink```?).
The second point is the task that is started to process what is put in the queue. I don't like it too much either and I'm wondering if there would be a way to use the explicit implementation of ```IProducerConsumerCollection<T>```. I didn't look into this too much so I will explore, but maybe someone already has an idea.
Let me know what you think.

Adding buffered boolean param to FileSink and RollingFileSink

---

src/Serilog/Core/Pipeline/Logger.cs

...so that it's clearly an implementation detail and not something we depend on accidentally.

A tiny internal change - make `Logger` implement `ILogEventSink` explicitly

---

src/Serilog/Configuration/LoggerEnrichmentConfiguration.cs
src/Serilog/Context/LogContext.cs
src/Serilog/LoggerConfigurationExtensions.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

From #593.
Took the opportunity to codify the series of fallbacks we want in LogContext implementation using the pattern:
```csharp
#if ASYNCLOCAL
// Preferred
#elif REMOTING
// Good but not everywhere
#else
// Must be DOTNET_51
#endif
```
Makes a positive difference to readability in that class.

Move `FromLogContext` to `LoggerEnrichmentConfiguration`, tidy some ifdefs

---

Build.ps1

Fixes #672
- Consolidated build/package of tests
- Use project specific package folders for `dnu pack`

Change to Build.ps1 to use separate package folders

---

src/Serilog.Sinks.ColoredConsole/Sinks/ColoredConsole/ColoredConsoleSink.cs

Fixes #649,
Strictly speaking, this is the _minimum_ in order to fix the issue. It uses the same lines as in ```MessageTemplateTextFormatter```, although in this case the if could be inverted.
I don't like it too much because this feels like duplicated logic, on the other hand ```ColoredConsoleSink``` needs to de-construct the message in order to apply different colours for different tokens.

Fixing ColoredConsoleSink to prevent printing empty properties

---

src/Serilog.Enrichers.Environment/Properties/AssemblyInfo.cs
src/Serilog.Enrichers.Process/Properties/AssemblyInfo.cs
src/Serilog.Enrichers.Thread/Properties/AssemblyInfo.cs
src/Serilog.Settings.AppSettings/Properties/AssemblyInfo.cs
src/Serilog.Sinks.ColoredConsole/Properties/AssemblyInfo.cs
src/Serilog.Sinks.Console/Properties/AssemblyInfo.cs
src/Serilog.Sinks.File/Properties/AssemblyInfo.cs
src/Serilog.Sinks.Observable/Properties/AssemblyInfo.cs
src/Serilog.Sinks.PeriodicBatching/Properties/AssemblyInfo.cs
src/Serilog.Sinks.RollingFile/Properties/AssemblyInfo.cs
src/Serilog.Sinks.TextWriter/Properties/AssemblyInfo.cs
src/Serilog.Sinks.Trace/Properties/AssemblyInfo.cs
src/Serilog/Properties/AssemblyInfo.cs

Fixes #687.
I didn't know if you wanted all assemblies `CLSCompliant` or just `Serilog.dll`, I've marked all of them in this repo, let me know if you want me to change it.

Mark assemblies CLSCompliant again

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/Formatting/Display/Casing.cs
src/Serilog/Formatting/Display/LiteralStringValue.cs
src/Serilog/Formatting/Display/LogEventLevelValue.cs
src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
src/Serilog/Formatting/Display/OutputProperties.cs
src/Serilog/Formatting/Display/Padding.cs
src/Serilog/Parsing/PropertyToken.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs
test/Serilog.Tests/Support/DelegatingSink.cs

#574 Now supports {Level,1} style syntax. Also supports upper/lower variations.

add fixed width functionality for log event output.

---

src/Serilog/Core/Logger.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

This PR communicates the dispose requirement of the logging pipeline by returning a concrete disposable type, `Logger`, from `CreateLogger()`.
One consequence is that `using` syntax can be applied:
```csharp
using (var log = new LoggerConfiguration()
.WriteTo.Console()
.CreateLogger())
{
// <app runs here>
}
```
It's not anticipated that users will generally wrap logger creation in a `using` block however; rather in 2.0 the `CloseAndFlush()` method will cover apps that base logging off of the static `Log` class.
```csharp
Log.Logger = new LoggerConfiguration()
.WriteTo.Console()
.CreateLogger();
// <app runs here>
Log.CloseAndFlush();
```
Doing this however clarifies at the API level that the logger needs to be flushed in some way. This is important as .NET Core doesn't expose any …

Make the return value of `LoggerConfiguration.CreateLogger()` concrete

---

src/Serilog/Core/IScalarConversionPolicy.cs

This interface is public, but no API allows an instance to be plugged in, so it is unusable as-is.
Internally, the implementation around this interface may have to change if the feature is ever opened up. Let's defer committing to a design for the public interface until the rest of the feature is fully planned out (if ever).
See discussion in #723.

Internalize IScalarConversionPolicy, since no API allows one to be plugged in

---

src/Serilog/Core/Logger.cs
src/Serilog/LoggerConfiguration.cs

Since the `Logger()` constructor is only called internally, and there's already a "sanitizing" `ToArray()` call covering the `IEnumerable<ILogEventEnricher>` supplied by the user in `ForContext()`, we can skip the one in `Logger`'s constructor:
```diff
-            _enrichers = enrichers.ToArray();
+            _enrichers = enrichers;
```

Removes a redundant `ToArray()` call from `ForContext()`

---

src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/ILogger.cs
src/Serilog/Log.cs
test/Serilog.Tests/Support/DisposableLogger.cs

#585 
Adds many methods to ILogger.
Removes one `params` array allocation per call, and potentially one boxing allocation per argument, for all `ILogger` methods of three or fewer parameters when logging for that level is off.
```csharp
var logger = new LoggerConfiguration()
.WriteTo.Sink(new DelegatingSink(e => { }))
.CreateLogger();
var sw = System.Diagnostics.Stopwatch.StartNew();
for (var i = 0; i < 10000000; ++i)
{
logger.Debug("Iteration {I}", i);
}
Console.WriteLine(sw.Elapsed);
```
Before: 0.153 seconds; after: 0.016 seconds.
Notes:
Ridiculously large and tedious change, needs another pair of eyes on it :-)

Add allocation-saving generic overloads to ILogger

---

src/Serilog/Core/Enrichers/EmptyEnricher.cs
src/Serilog/Core/Enrichers/SafeAggregateEnricher.cs
src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/Core/Sinks/FilteringSink.cs
src/Serilog/ILogger.cs
src/Serilog/Log.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Support/DisposableLogger.cs

The `ForContext()` set of methods are performance and allocation-sensitive because they're on the code path even when logging is off or at a level that produces few events. The change speeds up `ForContext()` by almost 4x in common usage.
This is one of three incoming 2.0 PRs that break `ILogger`, so ideally won't be merged until all three are ready.
**Adds `ForContext(ILogEventEnricher)` to `ILogger`, thus a breaking change.**
Impact should be low - will not break packages that consume `ILogger`, but will break code that implements it.
Most of the allocations were due to `ForContext()` requiring a list or enrichers - since most `ForContext()` calls are to add a single property, this is hugely wasteful - array allocations, iteration, etc.
The PR shifts `Logger` to call through a single …

Optimize ForContext() by removing allocations

---

src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/ILogger.cs
src/Serilog/Log.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Support/DisposableLogger.cs

Adds two methods to `ILogger`. Change 2 of 3.
A modification of Proposal 1 from #746
```csharp
MessageTemplate messageTemplate;
IEnumerable<LogEventProperty> properties;
if (!logger.BindMessageTemplate("Some {Number}", new object[] { 42 }))
return;
var evt = logger.CreateEvent(DateTimeOffset.Now, level, exception, messageTemplate, properties);
LogEventProperty ticksProperty;
if (logger.CreateProperty("Ticks", 123, false, out ticksProperty))
evt.AddOrUpdateProperty(ticksProperty);
LogEventProperty userProperty;
if (logger.CreateProperty("User", user, true, out userProperty))
evt.AddOrUpdateProperty(userProperty);
logger.Write(evt);
```
Not the prettiest API in the world, but:
* Keeps things orthogonal - there's already a public constructor on `LogEvent` so there's no need to return one
* …

Add BindMessageTemplate() and BindProperty() to ILogger

---

src/Serilog/Debugging/SelfLog.cs
test/Serilog.Tests/Debugging/SelfLogTests.cs

The `TextWriter`-based `SelfLog.Out` is hard to use on remote machines because there's no clear 'action' on which a freshly-written self-log event can be sent across the network. This patch obsoletes `Out` and replaces it with `Enable(Action<string>)`, `Enable(TextWriter)` and `Disable()`.
```csharp
// Old code
SelfLog.Out = file;
// New code
SelfLog.Enable(file);
// or
SelfLog.Enable(m => SendToSantaClaus(m));
```

Enable(action) for SelfLog

---

src/Serilog/Formatting/Display/LogEventLevelValue.cs
src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs

2.0 introduced support for short level names like `INF`, `inf` and so-on in output templates.
We initially used `,n` width specifiers, e.g. `"{Level,3:u}"` to generate a three-character uppercase level name. This required some deviation from the `IFormattable`-style formatting we use elsewhere, and is at odds with how `,n` padding values normally work in format strings.
This PR instead opts for a scheme matching e.g. how `Int32` hex formats specify width. The equivalent of the three-character uppercase example is `"{Level:u3}"`.
Lowercase is supported with `w`, e.g. `:w3` for three-character lowercase, and title case like `Inf` can be achieved using a `t` prefix, e.g. `:t3`.
Widths from 1 to 99 are handled, but values greater than 10 don't have any effect on the current set of level …

Switch from ,n level width specifiers to :tn

---

src/Serilog/Events/MessageTemplate.cs

By using a new method, similar to `Enumerable.OfType<TResult>` but faster.
My tests show it's ~2X or ~3X faster.

Improve message template construction performance

---

test/Serilog.Tests/Core/LogEventPropertyCapturingTests.cs
test/Serilog.Tests/Support/LogEventPropertyStructuralEqualityComparer.cs
test/Serilog.Tests/Support/LogEventPropertyStructuralEqualityComparerTests.cs
test/Serilog.Tests/Support/LogEventPropertyValueComparer.cs

The `LogEventPropertyStructuralEqualityComparer` and `LogEventPropertyValueComparer` currently only support `ScalarValue` and `SequenceValue`. If the comparer encounters a `StructureValue` or `DictionaryValue` it throws `NotImplementedException`.

Cover property capturing with better tests

---

src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

How to specify JSON format for file/rolling file output [is](http://stackoverflow.com/questions/37787339/controlling-settings-for-serilog-in-app-config) [an](http://stackoverflow.com/questions/37794854/how-to-set-formatprovider-property-in-serilog-from-app-config-file) [FAQ](http://stackoverflow.com/questions/32053859/how-to-specify-jsonformatter-in-web-config-for-serilog).
[Serilog.Sinks.Json](https://github.com/nblumhardt/serilog-sinks-json) helps but feels like a hacky workaround.
This PR adds the infrastructure that will allow sinks to use configuration like:
```xml
<add key="serilog:write-to:RollingFile.textFormatter" value="Serilog.Formatting.Json.JsonFormatter" />
```
This won't light up until the sinks add configuration overloads with appropriate parameters, but at least moves us …

Support setting values of interface types where a fully-qualified type name is supplied

---

.travis.yml
appveyor.yml

Previous PRs based on `dev`. 
* Specify version explicitly on all builds.
* Ensure that OSX and Nix are using `1.0.0-preview2-003121` (Currently inconsistent)
* Specify branch e.g. `rel/1.0.0-preview2` as location to source scripts.

Use env vars for clarity. Also ensure OSX and *nix using same version

---

src/Serilog/Core/Logger.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

This allows child loggers to increase verbosity, by bypassing the minimum level check in `Logger`'s (explicit) implementation of `ILogEventSink.Emit()`.
The approach taken here means that if a logger is cast to `ILogEventSink` clients of the logger could effectively do the same thing. If this is deemed an issue we could add a new internal interface to connect the logger chain instead of `ILogEventSink`, but in practice since `WriteTo.Logger()` uses `ILogger.Write()` there's no scenario today where this will be observable.

Fixes #815 - increasing level through overrides

---

src/Serilog/Formatting/Json/JsonFormatter.cs

`JsonFormatter` needs a cleanup. Some of the motivations are discussed in: https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/
This PR is a work-in-progress:

Deprecate virtual extension points of JsonFormatter (WIP)

---

src/Serilog/Configuration/LoggerAuditSinkConfiguration.cs
src/Serilog/Core/Sinks/AggregateSink.cs
src/Serilog/Core/Sinks/FilteringSink.cs
src/Serilog/LoggerConfiguration.cs
src/Serilog/Parameters/PropertyValueConverter.cs
src/Serilog/project.json
test/Serilog.Tests/Core/LogEventPropertyCapturingTests.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Events/LogEventPropertyValueTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs

#820 
Usage:
```csharp
Log.Logger = new LoggerConfiguration()
.WriteTo.Console()
.AuditTo.File("audit.txt")
.CreateLogger();
```
Exceptions raised by sinks configured through `AuditTo` will propagate out to the caller.
Sinks have to opt-in by overloading their configuration extension methods. This might lead to some code duplication and would be improved if `LoggerAuditSinkConfiguration` provided a helper method like `AsLoggerSinkConfiguration()` (trivial to write), but because it's part of the DSL we probably don't want this on the API surface. Doing it through an extension method (thus hiding it unless the namespace is included) would solve this but seems too hacky to be appealing.

Audit-style logging

---

src/Serilog/project.json
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/project.json

Back `LogContext` with the newer `AsyncLocal` where available (NET 4.6+) to avoid remoting issues. #835.

Use AsyncLocal rather than LogicalCallContext on .NET 4.6

---

src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
src/Serilog/project.json
test/Serilog.PerformanceTests/Serilog.PerformanceTests.xproj
test/Serilog.Tests/Serilog.Tests.xproj
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/project.json
test/TestDummies/DummyLoggerConfigurationExtensions.cs
test/TestDummies/DummyRollingFileAuditSink.cs
test/TestDummies/DummyRollingFileSink.cs

I'd somehow assumed this only needed downstream <appSettings> support, but of course the key-value pair settings are implemented in Serilog directly.
This PR enables:
```xml
<add key="serilog:audit-to:File.path" value="C:\\auditfile.txt" />
```
and so-on.

Support `audit-to` in key-value and thus in <appSettings> settings

---

src/Serilog/Context/LogContext.cs

`AppDomain.CurrentDomain.Id` will always return `1` in the default/entry appdomain, so the existing mitigation for remoting the log context won't work across processes.
Fixes #835

Ensure the per-AppDomain LogContext property name is unique across processes

---

src/Serilog/Configuration/LoggerDestructuringConfiguration.cs
src/Serilog/LoggerConfiguration.cs
src/Serilog/Parameters/PropertyValueConverter.cs
test/Serilog.Tests/Core/LogEventPropertyCapturingTests.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Events/LogEventPropertyValueTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs

Regarding #565.
I have done just string length limiting. When this will be completed I will move on to collections size limit as discussed in #565.
Things that need to be discussed:
a) default limit - for now I set it to 1000, but I am absolutely confortable to setting no limit by default(or int.MaxValue)
b) Whether we want to allow configuration of "truncation string". For now I used … (U+2026) without configuration. 
Ideas are welcomed.

Payload limiting 

---

README.md

I've had a shot at revamping the README.
When I check out a new library, the README is the first thing I look at. While our current README has links to all sorts of useful documentation, people will only bother clicking through and reading it if they can confirm Serilog matches what they're looking for first.
I think it'd be great to make this even more comprehensive, but this should at least be a decent starting point. Feedback welcome! :-)
[Rendered](https://github.com/nblumhardt/serilog/blob/fc900ba5d906d15445787a756f0e4c98eba81bd0/README.md)

A more informative and welcoming README

---

src/Serilog/Formatting/Json/JsonValueFormatter.cs
test/Serilog.Tests/Formatting/Json/JsonValueFormatterTests.cs

This fixes issue #885 where special floating point values are not properly formatted as JSON.
It adds an if statement to the JSON value formatter that catches the special values and formats them as JSON strings. In addition, it adds several unit tests that check if the special values are being formatted as JSON strings.

fix for Issue #885, formatting floating point special values NaN/PositiveInfinity/NegativeInfinity as JSON strings and unit tests

---

test/Serilog.Tests/Core/LoggerTests.cs

As proposed in #878, tests that check the convention of the log level wrapper methods in` Serilog.Core.Logger`. The tests reflect over the methods in `Serilog.Core.Logger` , that match known log level names. Then the methods and their parameters are checked against several rules that match the signatures listed below. If a method matches a know signature, it is invoked with some arbitrary data. If a method does not match a know signature, the test for its log level group fails with the unmatched method printed out as an error message.
```
Method0 (string messageTemplate) : void
Method1<T> (string messageTemplate, T propertyValue) : void
Method2<T0, T1> (string messageTemplate, T0 propertyValue0, T1 propertyValue1) : void
Method3<T0, T1, T2> (string messageTemplate, T0 propertyValue0, T1 …
```

Convention tests for log level write methods in Serilog.Core.Logger

---

src/Serilog/Log.cs

I found several differences in `Serilog.Log` versus the `Serilog.ILogger` interface. This PR brings `Serilog.Log` into parity with `Serilog.ILogger`.  
1.   `ForContext` method that takes multiple `ILogEventEnricher` takes an array versus `IEnumerable<ILogEventEnricher>` in `Serilog.ILogger`. This changes it so that it takes an `IEnumerable<ILogEventEnricher>`.
`ILogger ForContext(ILogEventEnricher[] enrichers)`  -->
`ILogger ForContext(IEnumerable<IlogEventEnricher> enrichers)`
2. Adds a `BindProperty` method to `Serilog.Log` 
`public static bool BindProperty(string propertyName, object value, bool destructureObjects, out LogEventProperty property)`

ILogger API conformance fixes in Serilog.Log

---

src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/AuditSinkTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

Also added test to cover this and moved audit sink related tests to a separate collection.

Dispose audit sinks on ILogger.Dispose()

---

Build.ps1

- fixes [#784](https://github.com/serilog/serilog/issues/784), related ES'[#49](https://github.com/serilog/serilog-sinks-elasticsearch/issues/49)
By default `--version-suffix` of `dotnet-pack` command flows to `--version-suffix` of `dotnet-build` command.
To overcome this `pr`'s propose  is to use `--no-build` switch on `dotnet-pack` so `--version-suffix` of `dotnet-pack` will affect only package/nuspec version. And `--version-suffix` of `dotnet-build` will only affect desired `AssemblyInformationalVersion`. 
The result is that
- when building on `master`  `AssemblyInformationalVersion` will look like `2.4.0-master-g3ff4af` and nuspec version will be **2.4.0**
- when building on `dev` `AssemblyInformationalVersion` will look like `2.4.0-dev-000042-g3ff4af` and nuspec version will be …

Include AssemblyInformationalVersion attribute to the with commit hash

---

test/Serilog.Tests/MethodOverloadConventionTests.cs

This PR, as per #878, adds convention/reflection based tests for the remaining methods defined in `Serilog.ILogger` i.e. `ForContext` and `BindMessage/Property`. It also adds support for testing `Serilog.Core.Pipeline.SilentLogger`.

Added tests for the rest of ILogger and added support for SilentLogger to Method Overload tests

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs

Enables `serilog:filter:Xyz` configuration directives. Cleaned up the code as much as possible in the process, so that `audit-to`, `write-to`, `enrich` and `filter` are consistently handled. Still some cleanup possible, but we're in better shape now :-)
Would support #924.

Refactor key-value settings to consistently apply configuration methods

---

.travis.yml

Entire rework of Travis builds for #824.
* Changed to use Travis OSX example from dotnet/docs. See  [details](https://github.com/dotnet/docs/blob/master/.travis.yml) here.
Alternative is to slightly update previous build config as seen [here](https://github.com/merbla/serilog/blob/enable-osx-for-travis/.travis.yml).

Enable builds for OSX on Travis #824

---

.travis.yml
appveyor.yml
build.sh
global.json

According to this link https://github.com/dotnet/cli/releases/latest, the current version is 1.0.1
If I do `File->New->Project(.NET Core: Console App)` then put `dotnet --version` in the pre-build event, I see `1.0.1`

Use dotnet core sdk 1.0.1

---

src/Serilog/Formatting/Display/OutputProperties.cs

Tiny, possibly insignificant improvement, but good to knock out allocations where we can.

Cache the {NewLine} literal property to avoid an allocation on each render

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs
test/TestDummies/DummyWrappingSink.cs

In our use of Serilog we'd like to be able to easily wrap existing sinks while also maintaining use of built-in extension methods. For example, we can create a decorator sink that adds the ability to disable sink output during runtime, and can be added to any existing sink.
This PR currently is a first pass on the API for this, so we can discuss the best approach for adding this in. The initial approach adds a new method to LoggerSinkConfiguration which accepts a callback to creating the wrapping Sink.

Sink wrapping

---

.travis.yml
appveyor.yml

* Update version of SDK on Travis to `1.0.4`
* Update AppVeyor image to VS 2017.

VS2017 Appveyor image and 1.0.4 SDK for Travis

---

src/Serilog/Context/LogContext.cs
src/Serilog/Core/Enrichers/FixedPropertyEnricher.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

This implements the suggestions in #733.
* `Push()` is just a naming fix - `PushProperties()` actually pushes a collection of enrichers
* `Clone()` lets worker threads opt-in to inheriting the parent's context stack

LogContext Push() and Clone()

---

src/Serilog/Parameters/PropertyValueConverter.cs
src/Serilog/Serilog.csproj
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

This PR for #965 converts tuples like `(1, 2, 3)` into arrays like `[1, 2, 3]` for consumption by sinks.
I don't think tuples are important enough, currently, to justify the effort of including another `LogEventPropertyValue` type to represent them. Arrays are a bit easier on the eyes than structures, and we don't lose any information since tuple member names aren't available dynamically.
The `@` operator is not required to capture a tuple. E.g.:
```csharp
Log.Information("{T}", (1, 2));
```
is fine. Specifying `@` will trigger deep serialization in the case of tuple members that are complex types.
The PR is a little ham-fisted (the change doesn't fit in as an `IScalarConversionPolicy`, unfortunately, so special treatment is needed). Only tuples up to length 7 are supported.
Since tuples …

ValueTuple to sequence value conversion

---

.github/PULL_REQUEST_TEMPLATE.md

The link in PULL_REQUEST_TEMPLATE.md pointed to a 404 (https://github.com/serilog/serilog/CONTRIBUTING.md)
No
- *N/A* Unit Tests for the changes have been added (for bug fixes / features)

Meta PR to fix PR Template

---

test/Serilog.Tests/Core/ChildLoggerTests.cs

Adds passing unit tests regarding child loggers, and more specifically around *namespace* overrides. This was done while working on issue #967 , in order to be sure I don't introduce any regressions ... 
Nope, it's only (passing) unit tests
I guess having some more tests cannot hurt :)
The failing tests (hopefully no longer failing!) will come as part of the issue's fix.

Added more (passing) tests about Child Loggers and overrides

---

Build.ps1

Can't see any reason not to use the build implicit in `dotnet pack`, please correct me if I'm missing anything.

Include source in package builds

---

src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Support/Some.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs
test/TestDummies/DummyWithLevelSwitchSink.cs

In order to support serilog/serilog-settings-appsettings#7

Support for LevelSwith in KeyValuePairSettings

---

test/Serilog.Tests/Settings/SettingValueConversionsTests.cs

The initial goal was to provide support for arguments of type `TimeSpan` in serilog-settings-appsettings (see issue serilog/serilog-settings-appsettings#9) .... But it turns out it is already supported, so I'll just contribute the tests that prove it :)
Nope. Only tests !
maybe the treatment for `TimeSpan` should be added to the documentation somewhere

Add test to prove proper support for TimeSpan in AppSettings

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/Core/Logger.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/ChildLoggerKnownLimitationsTests.cs
test/Serilog.Tests/Core/ChildLoggerTests.cs
test/Serilog.Tests/Support/Some.cs
test/Serilog.Tests/Support/TemporarySelfLog.cs

Related to #967 
This is a second PR  after comments on #1027 and discussion in #1032
The idea is that we no longer try to support `MinimumLevel.Override` in sub-loggers, but write to the `SelfLog` that it is not supported nor recommended, and using `.Filter` is better, or event better, the overrides of the root logger. 
No, it actually just makes it explicit that `MinimumLevel.Override` is not supported on sub-loggers
I'm not super convinced about the message written to SelfLog :) Review from a native English speaker would be nice :)

Make it clear that Sub-logger MinimumLevel.Override is not supported

---

Serilog.sln.DotSettings
src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Context/LogContext.cs
src/Serilog/Core/Pipeline/MessageTemplateCache.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs
test/TestDummies/DummyRollingFileAuditSink.cs
test/TestDummies/DummyRollingFileSink.cs
test/TestDummies/DummyWithLevelSwitchSink.cs
test/TestDummies/DummyWrappingSink.cs

Get rid of errors and warnings reported by ReSharper Solution-wide analysis
Nope
- *N/A* Unit Tests for the changes have been added (for bug fixes / features)
Before : 
After : 
There are still some warnings; but I was not sure how to fix them : 
```
Solution Serilog.sln
Project Serilog
src\Serilog\Capturing\PropertyValueConverter.cs:250 Possible 'System.NullReferenceException'
src\Serilog\Capturing\PropertyValueConverter.cs:250 Possible 'System.NullReferenceException'
src\Serilog\Context\LogContext.cs:257 Possible 'System.NullReferenceException'
src\Serilog\Core\Pipeline\MessageTemplateCache.cs:54 The field is sometimes used …
```

Make Resharper green again

---

test/Serilog.Tests/MethodOverloadConventionTests.cs

Remove some remaining ReSharper warnings in tests.
no. Impacts tests only
Some more warnings are left and will be fixed in PR #1051 (commit https://github.com/serilog/serilog/pull/1051/commits/6662f248b0d1cadfd8d2640c0986fa43fd804052 )

Remove more ReSharper warnings

---

src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs
test/Serilog.Tests/Support/ClassHierarchy.cs

When a parameter is an abstract class, now accept the type name of a concrete subclass that has a default constructor ( the same way interfaces are supported)
Resolves #1056 
This is the equivalent of serilog/serilog-settings-configuration#74
Nope

Add support for abstract class parameters in settings

---

src/Serilog/Configuration/LoggerSettingsConfiguration.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

new PR based on discussion https://github.com/serilog/serilog/pull/1047#issuecomment-338544876 .
Make `KeyValuePairSettings` accept a `IReadOnlyDictionary<string, string>` instead of a `IEnumerable<KeyValuePair<string, string>>` to make it more obvious that : 
- it is not consuming the key-value pairs lazily
- it expects unique keys
- it will not touch the contents of the provided dictionary
This has no impact on the public API given that class `KeyValuePairSettings` is `internal`.
This PR also adds a few tests around the edge cases

KeyValuePairSettings - IReadOnlyDictionary / latest setting win

---

src/Serilog/Configuration/LoggerSettingsConfiguration.cs
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs
test/Serilog.Tests/Support/ClassHierarchy.cs
test/Serilog.Tests/Support/CustomConsoleTheme.cs
test/Serilog.Tests/Support/StaticAccessorClasses.cs
test/TestDummies/Console/DummyConsoleSink.cs
test/TestDummies/Console/Themes/ConcreteConsoleTheme.cs
test/TestDummies/Console/Themes/ConsoleTheme.cs
test/TestDummies/Console/Themes/ConsoleThemes.cs
test/TestDummies/Console/Themes/EmptyConsoleTheme.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs

as a value for parameters, using the syntax `NameSpace.To.ConcreteType::StaticProperty, AssemblyName`
resolves #1057 
It shouldn't, although technically, there is a chance that "string" settings whose value looks like `"Namespace.To.TypeName::PropertyName"` may now be interpreted as a reference to a static property, even though I've done my best to avoid ambiguities.  
When / if accepted, similar code should be needed in *Serilog.Settings.Configuration* to handle issue serilog/serilog-settings-configuration#73 .

Add support for reference to public static properties in settings

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs

#1073 Overload Wrap() to accept LogEventLevel and LoggingLevelSwitch.

---

src/Serilog/Serilog.csproj

* Use HTTPS to avoid mixed content warning on nuget.org, and
* Point the project URL to GitHub.

Update package metadata URLs

---

build.cmd
global.json
src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
src/Serilog/Formatting/Display/Obsolete/LogEventPropertiesValue.cs
src/Serilog/Formatting/Display/PropertiesOutputFormat.cs
src/Serilog/Rendering/MessageTemplateRenderer.cs
src/Serilog/Serilog.csproj
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Core/SecondaryLoggerSinkTests.cs
test/Serilog.Tests/Debugging/SelfLogTests.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs
test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs
test/TestDummies/TestDummies.csproj

Fixes serilog/serilog-sinks-file#45 - support {Properties:j} in output templates; fixes #1088 - handle positional properties when computing {Properties}.
Brings the built-in message template formatting in line with _Serilog.Sinks.Console_.
Originally, `:j` wasn't supported on `{Properties}` because the formatting APIs here required some additional allocations in order to implement it, but in retrospect, better to be consistent.

Improvements to {Properties} handling in output templates

---

src/Serilog/Core/Logger.cs
test/Serilog.Tests/Core/LoggerTests.cs

Addresses issue #1105.  Replaces PR #1108 
No
Sorry for the new PR.  Given the changes in the old PR were in the completely wrong file, it seemed easier to just close that PR and open a new one.
Issue #1105 asked for an easy way to get at a constant instance of a `SilentLogger`. The original PR added this on the `Log` class and slightly adjusted that class' internals to make use of this instance.
This new PR instead modifies the `Logger` class to add a static `Logger.None` property that returns the same `SilentLogger`.
One new allocation overall.  I suspect we can live with that (?).  Former PR didn't have that issue.  A lazy init …

Fixes #1105 - add a static None property to the Logger class

---

test/Serilog.Tests/Context/LogContextTests.cs

fixes [1112](https://github.com/serilog/serilog/issues/1112)
- no

`ContextPropertiesCrossAsyncCalls` test failure fix on CI:

---

.travis.yml

Builds aren't tested on OSX, yet some developers actually like to use OSX to improve serilog.
No
Way back in #939 we disabled OSX builds because (at the time) Travis + OSX was quite unstable and causing regular issues. Now seems like a good time to try it again, and see if those issues still exist.

Enable OSX builds on travis again

---

appveyor.yml

Post moving to NuGet orgs (see #1159) a new key is needed to push packages.  Current [builds](https://ci.appveyor.com/project/serilog/serilog/build/977) are failing.
The API key has been created under the Serilog org in NuGet.
No

Updated NuGet API Key.

---

src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

Logger references to its configuration instance via `Dispose` closure that captures it.
No.
After checking implications of introducing new state (`.WriteTo`) for `LoggerConfiguration` in the neighboring [pr](https://github.com/serilog/serilog/pull/1165) found that current `CreateLogger()` captures `LoggerConfiguration` instances.

Created Logger should not hold reference to its configuration

---

Serilog.sln.DotSettings
src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

These were identified via the discussion in #1154.
- Ensures that `wt.X(); wt.Y()` and `wt.X().WriteTo.Y()` are equivalent
- Ensures a failing sink doesn't block events from reaching others inside the same wrapper, much as using a secondary logger would do
- Prevents chained calls from accidentally breaking thread-safety rules by turning `Enrich` inside wrappers into a no-op

Fixes a number of issues with `LoggerSinkConfiguration.Wrap()`

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
src/Serilog/Settings/KeyValuePairs/SurrogateConfigurationMethods.cs
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/TestDummies/DummyHardCodedStringDestructuringPolicy.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs

Supports Serilog "native" non-generic simple  methods : 
- `.ToMaximumDepth(int maximumDestructuringDepth)`
- `.ToMaximumStringLength(int maximumStringLength)`
- `.ToMaximumCollectionCount(int maximumCollectionCount)`
and also for any *extension method* for `LoggerDestructuringConfiguration`.
Unsupported methods (should they be added ? and how would they be configured ? ) : 
- `.AsScalar(Type scalarType)`
- `.AsScalar<TScalar>()`
- `.With(params IDestructuringPolicy[] destructuringPolicies)`
- `.With<TDestructuringPolicy>()`
- `.ByTransforming<TValue>(Func<TValue, object> transformation)`
- `.ByTransformingWhere<TValue>(Func<Type, bool> predicate, Func<TValue, object> transformation)`       
Most test cases adapted from equivalent PR in serilog/serilog-settings-configuration#110 (thanks …

Add partial support for .Destructure.XXX() methods in `KeyValuePairSettings`

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
src/Serilog/Settings/KeyValuePairs/SurrogateConfigurationMethods.cs
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs

This should fix #1177 
no
Adds support for key-value settings like : 
```xml
<add key="serilog:destructure:AsScalar.scalarType" value="MyNamespace.MyType, MyAssembly, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
```
As a side-effect, it also adds global support for calling **configuration methods that have a parameter of type `Type`**, by accepting the type name.
The type lookup relies on [`Type.GetType(string typeName, bool throwOnError)`](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.7.1#System_Type_GetType_System_String_System_Boolean_) (with `throwOnError` set to …

Support for .Destructure.AsScalar(scalarType) in KeyValueSettings

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs
src/Serilog/Settings/KeyValuePairs/SurrogateConfigurationMethods.cs
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/TestDummies/DummyReduceVersionToMajorPolicy.cs

fixes #1190
The key-value settings will accept the assembly-qualified name of a type implementing IDestructuringPolicy if it has a default constructor

Add support for Destructure.With(IDestructuringPolicy policy) in settings

---

src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/Log.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs

Fix #1195: This allows comparision Log.Logger = Logger.None
No, the change should not have any breaking effect to the clients
I do not believe it is appropriate/there is a need to override Equals() method as it is not a value type but I am happy to take any suggestions.

Allow SilentLogger to be contructed as singleton

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs
src/Serilog/Settings/KeyValuePairs/SurrogateConfigurationMethods.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Settings/CallableConfigurationMethodFinderTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/TestDummies/DummyAnonymousUserFilter.cs
test/TestDummies/DummyRollingFileAuditSink.cs
test/TestDummies/DummyRollingFileSink.cs
test/TestDummies/DummyThreadIdEnricher.cs
test/TestDummies/DummyWrappingSink.cs

implements #1194 
no
Adds support and tests for 
- `WriteTo.Sink(ILogEventSink logEventSink, LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum, LoggingLevelSwitch levelSwitch = null)`
- `AuditTo.Sink(ILogEventSink logEventSink, LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum, LoggingLevelSwitch levelSwitch = null)`
- `Enrich.With(params ILogEventEnricher[] enrichers)` (with surrogate `Enrich.With(ILogEventEnricher enricher)` )
- `Filter.With(params ILogEventFilter[] filters)` (with surrogate `Enrich.With(ILogEventFilter filter)` )

Config method support

---

src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs

Fixes https://github.com/serilog/serilog-sinks-rollingfile/issues/71
Could break parsing of log files that depends on the incorrect behavior; it looks like the issue was probably introduced about a year ago in https://github.com/serilog/serilog/commit/d2dd76d which shipped with Serilog 2.5.

Fix output template padding of non-String values

---

test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs

This PR adds tests about the current behavior of message templates when passing a custom `IFormatProvider`. 
There are no changes to the tested code.
Those tests are ported and adapted from https://github.com/serilog/serilog/pull/1183 and are related to https://github.com/serilog/serilog-sinks-file/issues/57#issuecomment-424154262 and https://github.com/serilog/serilog/issues/1115

Add tests around support of custom `IFormatProvider`

---

src/Serilog/Formatting/Display/LevelOutputFormat.cs

Hi!
During the profiling I found that `LogEventLevel` was boxed during [formatting](https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Display/LevelOutputFormat.cs#L55). You can see the evidence of the boxing in the screenshot :
Nope

Reduce LogEventLevel boxing

---

README.md

None - it adds a link to a list of Pluralsight courses (just uses search tag of "serilog") to the readme file.
No
(no unit tests added but not applicable)
Only a readme update.

added link to search of ps courses on readme

---

Directory.Build.props
appveyor.yml
src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj

The new recommended way to release debug symbols is separately, via `.snupkg` packages. This reduces package size, and conforms with NuGet's best practices.
The `.snupkg` files must be published in NuGet as well.

Use snupkg symbol packages.

---

src/Serilog/Rendering/MessageTemplateRenderer.cs
test/Serilog.Tests/Rendering/MessageTemplateRendererTests.cs

Fixes #1323 
We should check this against the behavior of https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/Rendering/ThemedMessageTemplateRenderer.cs before merging.

Respect explicit format specifiers even when JSON defaults are selected

---

src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs

Resolves issue #1328
It makes the last argument of a constructor optional.  I don't think that is breaking change.
- [NA] Unit Tests for the changes have been added (for bug fixes / features)

made formatProvider optional in the constructor of MessageTemplateTextFormatter

---

src/Serilog/Configuration/LoggerDestructuringConfiguration.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

The summary for the [`LoggerDestructuringConfiguration.ToMaximumDepth`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerDestructuringConfiguration.cs#L140) method incorrectly states that the default maximum destructuring depth is 5, when in fact the [default is 10](https://github.com/serilog/serilog/blob/dev/src/Serilog/LoggerConfiguration.cs#L41).
There is no Issue raised for this. Since it does not change any implementation and is such a minor change I assumed it would not be necessary. Let me know if this is not the case and I'll happily add one!
No. This is a documentation change only.
As well as …

Update summary for default destructuring depth

---

src/Serilog/Parsing/MessageTemplateParser.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

fixes  #1353 
No
The custom numeric format string mentioned in the bug was not parsed correctly because it contained a plus sign. The IsValidInFormat() function in the MessageTemplateParser did not consider '+' a valid character in format strings.

Fix custom format string parsing

---

setup.sh

Current Ubuntu1804 build failure; appears to be due to `dotnet-install.sh` moving.

Follow redirect to download dotnet-install.sh

---

test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

This PR is to Improve the *Code Coverage* for _Serilog.Parsing.*_
No
I didn't create a PR for this PR. This PR don't fix or add any functionality.
-  _Serilog.Parsing.MessageTemplateParser_ code coverage is now **100%**

Improve Serilog.Parsing Unit Tests and Code Coverage - Take 2

---

appveyor.yml

Symbols not published to the NuGet.org symbol server. Publishing was disabled early on due to some flakiness in the tooling (IIRC).
No

Reenable NuGet symbol publishing

---

src/Serilog/Capturing/PropertyValueConverter.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs

This will fix the issue #1426 - A bad designed Class can cause an Exception when logging with stringification operator.
No
- [ x ] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [ x ] Unit Tests for the changes have been added (for bug fixes / features)

Record stringified property as `null` when `ToString()` returns `null`

---

src/Serilog/Configuration/LoggerMinimumLevelConfiguration.cs

Updated docs for `LoggerMinimumLevelConfigration.Override()` to indicate that this API is not supported for configuration of sub-loggers.
Resolves #1444

Updated docs regarding LoggerMinimumLevelConfiguration.Override()

---

results/netcoreapp3.1/SourceContextMatchBenchmark-report-github.md
run_perf_tests.sh
src/Serilog/Core/LevelOverrideMap.cs
src/Serilog/Filters/Matching.cs
src/Serilog/Serilog.csproj
test/Serilog.PerformanceTests/Harness.cs
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.PerformanceTests/SourceContextMatchBenchmark.cs
test/Serilog.Tests/Filters/MatchingTests.cs

Optimization made on source context matching (`LevelOverrideMap`, `Match.FromSource()`) for `netstandard2.1`.
No
**Other information**
``` ini
BenchmarkDotNet=v0.12.0, OS=debian 11
Intel Core i7-3840QM CPU 2.80GHz (Ivy Bridge), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.1.201
[Host]     : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
Job-CSERBI : .NET Core 2.1.16 (CoreCLR 4.6.28516.03, CoreFX 4.6.28516.10), X64 RyuJIT
Job-GDNCBZ : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
```
|                             Method |       Runtime |       Mean |    Error |   StdDev | Ratio | …

Source context matching optimize

---

Serilog.sln.DotSettings
src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/Core/CustomDefaultMethodImplementationAttribute.cs
src/Serilog/Core/Sinks/AggregateSink.cs
src/Serilog/Core/Sinks/ConditionalSink.cs
src/Serilog/Core/Sinks/DisposeDelegatingSink.cs
src/Serilog/Core/Sinks/DisposeWrappingSink.cs
src/Serilog/Core/Sinks/DisposingSafeAggregateSink.cs
src/Serilog/Core/Sinks/FilteringSink.cs
src/Serilog/Core/Sinks/RestrictedSink.cs
src/Serilog/Core/Sinks/SafeAggregateSink.cs
src/Serilog/Core/Sinks/SecondaryLoggerSink.cs
src/Serilog/Events/EventProperty.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/Rendering/MessageTemplateRendererTests.cs
test/Serilog.Tests/Support/DelegatingLogger.cs

* Breaks the inheritance relationship between `SafeAggregateSink` and `DisposingSafeAggregateSink` - generally we're aiming to avoid inheritance wherever we can
* Merges #1449 from @augustoproiete - `DisposingSafeAggregateSink` should be `DisposingAggregateSink`, so that wrapper sinks can observe exceptions in more cases
* Renames `DisposeWrappingSink` to `DisposeDelegatingSink` and removes a level of indirection, since the introduction of the disposing aggregate sink means that the enclosed/wrapped sink will always be `IDisposable` in the case that disposal is required
* Some tidy-up based on Rider's latest suggestions...

Refactor wrapper sinks

---

src/Serilog/Configuration/LoggerAuditSinkConfiguration.cs
src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Core/ChildLoggerTests.cs

Fixes #1346 , #1453 
Behavior change for subloggers configured inline when no explicit default level specified for them.
**Other information**
Inheriting minimum level was done before overrides where introduced, so it doesn't take them into account now for subloggers which results in counterintuitive behavior.

Don't inherit parent Minimum Level for inline sublogger configuration

---

src/Serilog/Configuration/LoggerDestructuringConfiguration.cs

This fixes a small mistake in the `AsScalar` set of destructuring methods' comments.
- "...event when..." to "...even when..."

Fix miswording on 'AsScalar' destructuring methods

---

src/Serilog/Core/Logger.cs

Processing of message template can take a bit of time and it offsets the real timestamp of log event.
I catch max additional offset about 12 milliseconds with small testing

more precise logevent timestamp

---

src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Debugging/SelfLogTests.cs

- Writes a warning message in `SelfLog` when a setting is found to have no implementation in any of the loaded assemblies
- Helpful when a user misses a `using` reference
Fixes #1539

Write to SelfLog to warn about settings with missing assembly references

---

src/Serilog/Serilog.csproj

Shouldn't need to be conditional this way - the `net5.0` version of Nullable ships nothing; the `netstandard2.1` version still supplies a couple of attributes (IIRC ;-)).

Make Nullable a private dependency; squeeze in a net5.0 target

---

src/Serilog/Core/Logger.cs
src/Serilog/ILogger.cs
src/Serilog/Serilog.csproj
test/Serilog.PerformanceTests/BindingBenchmark.cs
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

No idea how this got through CI, but the build on `dev` is broken because of a missing `FEATURE_DEFAULT_INTERFACE` define for net5.0 (my bad :-))

Fix testing of net5.0 target; disallow warnings in test projects

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Policies/ByteMemoryScalarConversionPolicy.cs
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

(ReadOnly)Memory<byte> scalar policy; NotSupportedExeption handling for PropertyValueConverter

---

src/Serilog/Core/MessageTemplateFormatMethodAttribute.cs

The example in the documentation was using a wrong name for the attribute. Corrected the usage in the example

Corrected Example in MessageTemplateFormatMethod documentation comments

---

src/Serilog/ILogger.cs

Reverts serilog/serilog#1664
@erichiller strange that your earlier PR didn't fail in CI - a number of the `<code>` blocks were malformed (closed with `<code>` instead of `</code>`).
The `dev` branch is now failing to build because of this, so reverting until we can redo it:
https://ci.appveyor.com/project/serilog/serilog/branch/dev
Cheers!

Revert "Update ILogger XML documentation"

---

src/Serilog/Core/Enrichers/PropertyEnricher.cs
src/Serilog/Core/ILogEventPropertyFactory.cs

Fixes https://github.com/serilog/serilog/issues/1686, and preempts a similar issue with `ILogEventPropertyFactory`.
Thanks for reporting this @taspeotis 👍

Fix #1686 - nullable annotations for PropertyEnricher

---

src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj

`VALUETUPLE` was being used but not defined in any constants
```
#if VALUETUPLE
if (definition == typeof(ValueTuple<>) || definition == typeof(ValueTuple<,>) ||
definition == typeof(ValueTuple<,,>) || definition == typeof(ValueTuple<,,,>) ||
definition == typeof(ValueTuple<,,,,>) || definition == typeof(ValueTuple<,,,,,>) ||
definition == typeof(ValueTuple<,,,,,,>))
#else
// ReSharper disable once PossibleNullReferenceException
if (definition.FullName is
"System.ValueTuple`1" or
"System.ValueTuple`2" or
"System.ValueTuple`3" or
"System.ValueTuple`4" or
"System.ValueTuple`5" or
"System.ValueTuple`6" or
"System.ValueTuple`7")
#endif
```

add missing VALUETUPLE check

---

src/Serilog/Context/LogContextEnricher.cs
src/Serilog/Core/Filters/DelegateFilter.cs
src/Serilog/Core/IDestructuringPolicy.cs
src/Serilog/Core/Pipeline/MessageTemplateCache.cs
src/Serilog/Policies/DelegateDestructuringPolicy.cs
src/Serilog/Policies/ProjectedDestructuringPolicy.cs
src/Serilog/Policies/ReflectionTypesScalarDestructuringPolicy.cs
test/TestDummies/DummyHardCodedStringDestructuringPolicy.cs

- LogContextEnricher.cs
- DelegateFilter.cs
- IDestructuringPolicy.cs
- MessageTemplateCache.cs
- DelegateDestructuringPolicy.cs
- ProjectedDestructuringPolicy.cs
- ReflectionTypesScalarDestructuringPolicy.cs

some more nullables

---

src/Serilog/Context/EnricherStack.cs
src/Serilog/Context/LogContext.cs

with the intent of making nullability easier to reason about in the next PR

rename ImmutableStack<ILogEventEnricher> to EnricherStack

---

Directory.Build.props

so we dont get 
```
[NETSDK1138] The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. 
Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
```

suppress CheckEolTargetFramework

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Configuration/LoggerSinkConfiguration.cs
src/Serilog/Context/LogContext.cs
src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/MessageTemplateCache.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/Core/Sinks/ConditionalSink.cs
src/Serilog/Core/Sinks/DisposeDelegatingSink.cs
src/Serilog/Core/Sinks/DisposingAggregateSink.cs
src/Serilog/Core/Sinks/RestrictedSink.cs
src/Serilog/Core/Sinks/SecondaryLoggerSink.cs
src/Serilog/GlobalUsings.cs
src/Serilog/Log.cs
src/Serilog/LoggerConfiguration.cs
src/Serilog/Serilog.csproj
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Core/ChildLoggerKnownLimitationsTests.cs
test/Serilog.Tests/Core/ChildLoggerTests.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Core/SecondaryLoggerSinkTests.cs
test/Serilog.Tests/GlobalUsings.cs
test/Serilog.Tests/LogTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Support/AsyncDisposeTrackingSink.cs
test/Serilog.Tests/Support/DisposableLogger.cs
test/Serilog.Tests/Support/DisposeTrackingSink.cs

Resolves https://github.com/serilog/serilog/issues/1749
This is admittedly very heavy on `#if`. We may be able to do better by polyfilling `IAsyncDisposable` and `ValueTask` for older platforms - keen to explore this, too.
Gets some tests and feature flags in place, though, which should be a good start. Eyes appreciated :-)

Initial support for `IAsyncDisposable` sinks

---

src/Serilog/Capturing/DepthLimiter.cs
src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Events/ScalarValue.cs

Introduce ScalarValue.Null

---

src/Serilog/Formatting/Json/JsonFormatter.cs

What do you think about exposing this property in public API? The same problem as in #1769 for Serilog.Sinks.Console: `foreach (var token in template.Tokens) ` usages in `OutputTemplateRenderer`, `PropertiesTokenRenderer` and `ThemedMessageTemplateRenderer`.

Tokens -> TokenArray

---

src/Serilog/Serilog.csproj

I believe it's time to give the project a refresh; a new major version is a good marker for this, but I should be clear at the outset we won't be making any ecosystem-splitting breaking changes (all existing sinks, enrichers, and so on should continue to work as before).
In particular, for 3.0 I'm anticipating we:
* Drop seriously out-of-date framework targets (`netstandard1.x`, and potentially full framework)
* Drop obsolete APIs or upgrade obsoletions to error rather than warning where sink dependencies may exist
* Consider behavioral changes currently recorded against the [3.0 milestone](https://github.com/serilog/serilog/milestone/13)
Along with this I think we'd ship a set of _Serilog.Extensions.*_ and _Serilog.AspNetCore_ packages that lock their versions to the framework versions …

Major version bump; opens dev for v3 development

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs

more readable, and avoids an allocation

remove duplicate Wheres in FindConfigurationMethods

---

src/Serilog/Settings/KeyValuePairs/CallableConfigurationMethodFinder.cs

better perf and simpler code by avoiding the GetTypeInfo and redundant methods included in DeclaredMethods

remove typeinfo from FindConfigurationMethods

---

src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs

* better perf and simpler code by using binding flags instead of Declared*
* simplify through removal of typeinfo (typeinfo  no longer need since our removal of older netstandards)

simplify reflection in SettingValueConversions

---

src/Serilog/Capturing/GetablePropertyFinder.cs

* removes a nested loop
* removes a lambda allocation
* remove the use of typeinfo. we no longer need it. means we can use bindingflags (which DeclaredProperties uses internally anyway) but can specify flags we want and remove some extra checks
* use FlattenHierarchy to avoid the basetype hierarchy walk

improve GetPropertiesRecursive

---

src/Serilog/Formatting/Json/JsonFormatter.cs

* less string alloc
* allow the underlying writer to optimize for a char instead of a 1 length string

Leverage null char in JsonFormatter

---

src/Serilog/Formatting/Json/JsonFormatter.cs

Also get rid of `string.Format` in `WriteRenderings` and `WriteProperties`.

Use correct overload with char in JsonFormatter

---

Build.ps1
Directory.Build.props
build.sh
src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj

* fixes on mac and linux that we were missing test runs on net7 and net6
* removes redundant restore = faster CI
* remove redundant `dotnet --info`. we already get that from the dotnet install script in appveyor.yml
* avoids extra build+restore that happen when u test if u omit  `--no-build --no-restore` = faster CI
* less code

simplify build scripts

---

src/Serilog/Parsing/MessageTemplateParser.cs
src/Serilog/Parsing/MessageTemplateToken.cs
src/Serilog/Parsing/PropertyToken.cs
src/Serilog/Parsing/TextToken.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

@nblumhardt any ideas what MessageTemplateToken.StartIndex is for? it doesnt seem to be used in the code. and i cant see how it would add value to a consumer of serilog

remove MessageTemplateToken.StartIndex

---

Build.ps1

Fixes #1850
Instead of specifying a build script directly, `appveyor.yml` specifies a fragment of PowerShell that calls the build script. Build failures will only bubble up and cause this outer script to fail if they `throw`, since PowerShell largely ignores exit codes.

Throw, rather than exit, when any command in the build script fails

---

Build.ps1
src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.ApprovalTests/ApiApprovalTests.cs
test/Serilog.ApprovalTests/Serilog.approved.txt

I just switched Seq over to Serilog 3 dev and the latest versions of our dependencies, but because of some transitive dependencies in the build I hit:
```
System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.Configuration.LoggerSinkConfiguration.Sink(Serilog.Core.ILogEventSink, Serilog.Events.LogEventLevel)'.
at Serilog.SeqLoggerConfigurationExtensions.<>c__DisplayClass3_0.<Seq>b__0(LoggerSinkConfiguration wt)
at Serilog.Configuration.LoggerSinkConfiguration.Wrap(LoggerSinkConfiguration loggerSinkConfiguration, Func`2 wrapSink, Action`1 configureWrappedSink, LogEventLevel restrictedToMinimumLevel, LoggingLevelSwitch levelSwitch)
at Serilog.Configuration.LoggerSinkConfiguration.Conditional(Func`2 condition, Action`1 configureSink)
at …
```

Reinstate `LoggerSinkConfiguration.Sink(ILogEventSink, LogEventLevel)`

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Core/ChildLoggerDisposalTests.cs

Closes #1447: we can simply proxy a parameter to `SecondaryLoggerSink` to make this work.
The one thing I'm not so sure here is related to the public API change. I've decided to add a new overload method so that the older `WriteTo.Logger(logger, restrictedToMinimumLevel)` wouldn't break, but maybe I'm missing something less evident (or more preferable) here.

Adding ability to dispose nested loggers in WriteTo.Logger

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.ApprovalTests/ApiApprovalTests.cs
test/Serilog.ApprovalTests/Serilog.approved.txt

This overload was introduced in #1890, so there's no compatibility concern here.

Accept/pass through the standard `levelSwitch` option in `WriteTo.Logger()`

---

src/Serilog/Capturing/PropertyBinder.cs
test/Serilog.Tests/Capturing/GettablePropertyFinderTests.cs
test/Serilog.Tests/Debugging/SelfLogTests.cs

Fixes #1464
The change is in `PropertyBinder`, but the tests (somewhat lazily) rely on `SelfLog`, so I've placed them alongside the others that will interact with it.

Fix #1464, don't log parameter count mismatch message incorrectly

---

src/Serilog/Events/LevelAlias.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/LoggerConfigurationTests.cs

The question of what to do about turning logging completely off via a `MinimumLevel.Override`, and how to map MEL's `LogLevel.Off` in configuration, has been open for a long time.
The arguments against putting this on `LogEventLevel` center around `Off` not being a valid value to find attached to a `LogEvent`.
This PR is an attempt to side-step the issue via `LevelAlias`. Adding `Off` here doesn't sanction constructing an event with the `Off` level, but gives us and everyone else an indication that the `Off` value will be respected in minimum level overrides and JSON configuration (some downstream work required in _Serilog.Settings.Configuration_ for this).
What do you think?

Add `LevelAlias.Off`; fixes #1684

---

src/Serilog/Formatting/Json/JsonFormatter.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs

Since 3.0 removes all the obsolete `JsonFormatter` virtual methods, we can now seal this and remove the duplicated functionality that existed solely for subclass use.
Feeling like this one's a decent win :-)

Use `JsonValueFormatter` to implement classic `JsonFormatter`

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Policies/PrimitiveScalarConversionPolicy.cs
test/Serilog.PerformanceTests/PipelineBenchmark.cs

Optimization for `PropertyValueConverter`. Skips hashset lookup in `SimpleScalarConversionPolicy` for primitive types. The [primitive types](https://learn.microsoft.com/en-us/dotnet/api/system.type.isprimitive?view=net-7.0#remarks) are Boolean, Byte, SByte, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Char, Double, and Single.
It additionally handles `sbyte`, `nint`, `nuint`, but these types could be excluded with additional check without performance penalty. I'm not sure if `sbyte` was originally excluded on purpose.
```cs
type.IsPrimitive && type != typeof(sbyte) && type != typeof(IntPtr) && type != typeof(UIntPtr)
// or
type.IsPrimitive && Type.GetTypeCode(type) is not TypeCode.Object and not TypeCode.SByte
```
Before:
|        Method |     Mean |   Error |  StdDev | …

PropertyValueConverter optimization: avoiding hashset lookup for primitive types

---

Serilog.sln
Serilog.sln.DotSettings
src/Serilog/Core/Logger.cs
src/Serilog/Events/LogEvent.cs
src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
src/Serilog/Formatting/Display/OutputProperties.cs
src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/ILogger.cs
src/Serilog/Serilog.csproj
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.PerformanceTests/PipelineBenchmark.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Events/LogEventTests.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Support/Some.cs

Fixes #1923
Fixes https://github.com/serilog/serilog-aspnetcore/issues/207
Note that trace and span ids will only be collected when at least one activity listener is present - this will be the case in just about all practical implementation scenarios right now, I think, but is still worth bearing in mind.
The addition of `{TraceId}` and `{SpanId}` to `MessageTemplateTextFormatter` is technically a breaking change; existing user templates with top level trace and span properties will now pull in the values from `LogEvent` rather than identically-named properties. In most cases these will have the same value/representation, so I don't think it justifies a major version bump, though it'd need a prominent call-out in the release notes.
The immediate benefit from merging this PR will be the …

Collect and propagate current trace and span ids through `LogEvent`

---

src/Serilog/Capturing/PropertyValueConverter.cs

Fixes build without `FEATURE_ITUPLE` constant defined.
> `Error IL2070 : 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields' in call to 'System.Type.GetFields(BindingFlags)'. The parameter 'type' of method 'Serilog.Capturing.PropertyValueConverter.TryConvertValueTuple(Object, Type, Destructuring, out LogEventPropertyValue)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.`

Added missing DynamicallyAccessedMembers in PropertyValueConverter

---

src/Serilog/Capturing/MessageTemplateProcessor.cs
src/Serilog/Capturing/PropertyBinder.cs
src/Serilog/Core/Logger.cs
src/Serilog/Core/PropertiesInlineArray.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs

Similar to https://github.com/serilog/serilog/pull/1779, but uses on-stack allocation instead of pooling.

Removed temporary array allocations for properties

---

src/Serilog/Core/Pipeline/ByReferenceStringComparer.cs
src/Serilog/Core/Pipeline/MessageTemplateCache.cs
test/Serilog.PerformanceTests/Support/ConcurrentDictionaryTemplateCache.cs
test/Serilog.PerformanceTests/Support/DictionaryMessageTemplateCache.cs

Related issue: https://github.com/serilog/serilog/issues/1946

By reference string comparison in template cache

---

src/Serilog/Rendering/ReusableStringWriter.cs

Fixes https://github.com/serilog/serilog/issues/1963 
StringBuilderCapacityThreshold is subject to discuss

ReusableStringWriter: Dispose instance with too big buffer

---

src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj
test/TestDummies/TestDummies.csproj

Removes test coverage for unsupported fameworks per https://github.com/serilog/serilog/issues/1970

chore: Drop test coverage for out of support .NET Core vers

---

CONTRIBUTING.md
Directory.Build.props
README.md

related: https://github.com/serilog/serilog/issues/1966
- Remove year (2020) from copyright message on readme (note this propagates to nuget)
- Remove mention of gitter (it's not well-monitored, so better to have people use GitHub issues and/or PRs to to/fro ideas)
- Added NuGet package copyright (see far bottom right of https://www.nuget.org/packages/equinox)
Open issues:
I feel the best answer is to remove them in favor of having one copyright year range in the NOTICE. This seems to be valid based on https://www.apache.org/legal/apply-license.html#copy-per-file and general SO searching. If this is not agreed, perhaps I could remove them from the test files only?
Failing that, I can add the header to all source files.

chore(docs): Markdown housekeeping

---

src/Serilog/Rendering/ReusableStringWriter.cs
src/Serilog/Serilog.csproj

* #1977 - don't stack overflow when disposing `ReusableStringWriter` with large renderings (@nblumhardt)

3.1.1 Release

---

src/Serilog/Core/LevelOverrideMap.cs
test/Serilog.Tests/Core/LevelOverrideMapTests.cs

Fix #1944.
Changes `LevelOverrideMap.GetEffectiveLevel()` to use a case-insensitive comparison for context names, correcting some challenges with setting overrides through mechanisms like environment variables where ALL_CAPS may be used.

Level override check is case-insensitive.

---

src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
src/Serilog/Formatting/Display/OutputProperties.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs

Add the **UtcTimestamp** token to the MesageTemplateFormatter, allowing for built in support of logging timestamps in UTC in custom formats without having to use the various workarounds (expressions/custom properties etc). Also added a small unit test to show that the correct value is output, and with a custom format.

Add a UtcTimestamp token and a small unit test

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Configuration/LoggerSettingsConfiguration.cs
src/Serilog/Configuration/TrimConfiguration.cs
src/Serilog/ILLink.Substitutions.xml
src/Serilog/Serilog.csproj
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/AotTestApp/AotTestApp.csproj
test/AotTestApp/Program.cs
test/AotTestApp/README.md
test/Serilog.ApprovalTests/Serilog.approved.txt

There's one trim warning that the analyzer didn't catch (bug) that the
AOT compiler does. Unfortunately, the warning isn't easily resolvable --
it implies that you can no longer use deconstructed compiler-generated
types (like anonymous types) through the various logging calls.
There's unfortunately no way to perfectly resolve this. This PR proposes
a behavioral change for trimming -- when trimming, compiler-generated
types will be logged like scalars, instead of being deconstructed. This
is not ideal. Libraries should not have significantly different behavior
when trimming without a warning or some other diagnostic being produced.
Unfortunately, the contract implied by the existing code is much too
complicated to be encoded in the trimmer. The contract is that types do
not need to …

Finish trim annotation

---

src/Serilog/Configuration/BatchingOptions.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Core/BatchingSinkTests.cs

Organized under `Serilog.Configuration` but pulled through an earlier namespace choice.

Fix the namespace of the new `BatchingOptions` type

---

src/Serilog/Configuration/LoggerSinkConfiguration.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Configuration/LoggerConfigurationTests.cs
test/Serilog.Tests/Configuration/LoggerSinkConfigurationTests.cs
test/Serilog.Tests/Core/AuditSinkTests.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs

Serilog sinks push for factory methods for sink construction and composition (`WriteTo.File()`), rather than an "OO" style of public sink types and constructors (`new FileSink(...)`).
The existing `LoggerSinkConfiguration.Wrap()` method is a helper used by wrapping sink implementations, such as _Serilog.Sinks.Async_, and the core `WriteTo.Conditional()` method, to enclose one or more sinks in a "wrapper" that modifies their behavior in some way.
The existing `Wrap()` method has three roles: providing access to the enclosed sinks created via their factory methods, delegating `IDisposable.Dispose()` to the enclosed sinks so that wrappers don't need to implement it explicitly, and applying a `LoggingLevelSwitch`/minimum level to the completed result.
This PR pulls out the two main …

Redesign `LoggerSinkConfiguration.Wrap()`, and introduce `LoggerSinkConfiguration.CreateSink()`

---

.gitignore
src/Serilog/Parsing/MessageTemplateParser.cs
test/Serilog.PerformanceTests/MessageTemplateParsingBenchmark.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

This PR came out of, and includes, #1384. You can read about the reasons for considering `.` in message template property names, and the various caveats/disadvantages on that thread. The PR enables wider investigation and experimentation, and there is currently no guarantee that this will ever become a first-class, supported Serilog feature.
By setting the experimental and **unsupported** `AppContext` switch at program start-up:
```csharp
AppContext.SetSwitch("Serilog.Parsing.MessageTemplateParser.AcceptDottedPropertyNames", true)
```
Placeholders such as `{http.request.method}` will (should!) be accepted in message and output templates. Previously, these templates would have been regarded as invalid.
Dotted placeholders will be interpreted as literal property names, e.g. …

`MessageTemplateParser` refactor incl. experiemental `.` support

---

src/Serilog/Parsing/MessageTemplateParser.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

Hey it's me again!
The existing implementation used .IsPunctuation + IsLetterOrDigit with an override for '+' and ' '. That left some conspicuous holes and the spec itself is just "^\}" so basically anything goes in a format string. This allows for them and this does seem to have a reasonably large impact on the DefaultConsoleOutputTemplate parsing method. Everything else was within error bounds and no impact at all on memory allocs.
Some examples of oddities was that `@` was allowed but `$` wasn't and `+` was allowed but `>, <, =` weren't
for posterity this is based on our conversation here: https://github.com/messagetemplates/grammar/pull/6
|               Method |         Mean |      Error |     StdDev |  Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|--------------------- …

fix: allows all non-'}' characters as format values

---

src/Serilog/Serilog.csproj
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/VersioningTests.cs

Fixes #2074 
This is essentially a commitment to strong binary backwards/forwards compatibility between all versions in a `Major.Minor` series.

Version `Serilog.dll` as `Major.Minor.0.0`

---

src/Serilog/Capturing/GettablePropertyFinder.cs
src/Serilog/Capturing/PropertyValueConverter.cs
test/Serilog.Tests/Capturing/GettablePropertyFinderTests.cs

An old refactor pulled out structure capturing logic into a method incorrectly named `TryConvertCompilerGeneratedType`; this in fact is the catch-all for non-scalar/dictionary/enumerable types without an explicit `IDestructuringPolicy` configured.
The misleading name led to incorrect logic being implemented for skipping capturing of compiler-generated type properties when not supported: in this situation all structure capturing will be skipped.
This PR fixes the method name - `TryConvertStructure` - and the aforementioned trimming-related logic.

Allow non-anonymous-type destructuring when trimmed

---

src/Serilog/Events/ScalarValue.cs
src/Serilog/Rendering/ReusableStringWriter.cs
test/Serilog.Tests/Formatting/Display/MessageTemplateTextFormatterTests.cs

This PR removes allocations from legacy (but still not deprecated in Console/File sinks) `MessageTemplateTextFormatter`. This may still be useful, since the timestamp is serialized for each log event.
Allocations:
- `DateTimeOffset` boxing, by adding `ScalarValue.Render<T>` overload with constraint for `IFormattable`
- `DateTimeOffset.ToString()` allocation, by using `ISpanFormattable.TryFormat` API
| Method         | Job      | Runtime  | Mean     | Error   | StdDev  | Gen0   | Allocated |
|--------------- |--------- |--------- |---------:|--------:|--------:|-------:|----------:|
| FormatToOutput | .NET 8.0 | .NET 8.0 | 184.9 ns | 1.93 ns | 1.81 ns | 0.0143 |     120 B |
| FormatToOutput | .NET 9.0 | .NET 9.0 | 141.3 ns | 1.50 ns | 1.40 ns | 0.0143 |     120 B |
| Method         | Job …

Removed boxing and string allocations in MessageTemplateTextFormatter

---

src/Serilog/Capturing/PropertyValueConverter.cs
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs

Fixes #2102 
I suspect this is also the cause of #2087 (CC @rcollette).

Don't capture properties with private `get` accessors

---

src/Serilog/Log.cs
test/Serilog.Tests/Core/BatchingSinkTests.cs
test/Serilog.Tests/LogTests.cs
test/Serilog.Tests/Support/DisposableLogger.cs
test/Serilog.Tests/Support/InMemoryBatchedSink.cs
test/Serilog.Tests/Support/SyncDisposableLogger.cs

This fixes #2115.
We've missed spotting this previously because the default `Logger` type _is_ `IAsyncDisposable`, and handles the fallback to `IDisposable` for sinks that don't implement it.

Fall back to `IDisposable` in `Log.CloseAndFlushAsync()` when the target logger is not `IAsyncDisposable`

---

src/Serilog/Configuration/BatchingOptions.cs
src/Serilog/Core/Sinks/Batching/BatchingSink.cs
src/Serilog/Core/Sinks/Batching/FailureAwareBatchScheduler.cs
src/Serilog/Util/TimeProvider.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Core/FailureAwareBatchSchedulerTests.cs
test/Serilog.Tests/Support/TestTimeProvider.cs

This PR improves batching sink behavior by making the retry time for failed batches explicit and configurable, through `BatchingOptions.RetryTimeLimit`. Previously, the retry time was computed from `BufferingTimeLimit` in a fairly opaque manner.
Batching still uses exponential back-off, and checks "expected" retry times against the limit, so the final retry for a batch may happen earlier than the configured maximum. The maximum granularity of retries is now 1 minute, so this puts an upper bound on the difference between the retry time limit and the actual last retry.
The failure sequence is:
- If no failures have occurred, collect and send batches within BufferingTimeLimit (two seconds by default)
- When the first failure occurs, retry at max(BufferingTimeLimit, five seconds) later, …

Add `BatchingOptions.RetryTimeLimit`

---

.github/workflows/ci.yml
Build.ps1

#2129 was unsuccessful, causing publishing to also be skipped on branch builds that resulted from a PR close.

Attempt to avoid building PR syncs, number 2

---

.github/workflows/ci.yml
Build.ps1

Reverts #2130 and #2129 - both prevented regular branch builds.
Will revisit.

Give up on skipping sync builds for now

---

.github/workflows/ci.yml
Directory.Version.props
global.json
src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Core/Logger.cs
src/Serilog/Serilog.csproj
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

See https://github.com/serilog/serilog/issues/2137
I've tentatively bumped the minor version to 4.2 to reflect the addition of an explicit 9.0 target, though no functional features are in there (yet).

.NET 9 SDK and TFM updates

---

appveyor-perftest.yml
src/Serilog/Parsing/MessageTemplateParser.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

This PR continues on from #2063, which enables `{a.b}`-style placeholders in message templates. The major benefit of this is to support environments that have standardized on [OpenTelemetry](https://opentelemetry.io/docs/specs/semconv/), [DataDog](https://docs.datadoghq.com/standard-attributes/), or [ECS-style](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html) naming schemes.
Dotted names, which are captured as _flat_ property names by Serilog, are compatible with a good slice of the Serilog ecosystem, but not all of it. Enough Serilog-based sinks, libraries and tooling will work with dotted names that these should be immediately usable by a majority of users. The process of finding and fixing problems when dots appear in property names may take some time, but can …

Stabilize and fully-implement dotted property names in message templates

---

src/Serilog/Events/LogEvent.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Configuration/LoggerConfigurationTests.cs

In this PR I propose to set public this internal method overload:
```
LogEvent.AddPropertyIfAbsent(ILogEventPropertyFactory factory, string name, object? value, bool destructureObjects = false)
```
The goal is allow to write optimised `ILogEventEnricher`classes and also to be able to use `ILogEventPropertyFactory` to create properties.
In therm of performance this solution would be almost the same as the code suggested in https://github.com/serilog/serilog/issues/739 where properties are created only once, but with the benefit of using the property factory as intended by the `ILogEventEnricher` interface. 
Example:
```
class SampleEnricher(Foo foo) : ILogEventEnricher
{
public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
{
// a LogEventProperty object is …
```

Property factory as AddPropertyIfAbsent parameter

---

src/Serilog/Context/LogContext.cs
src/Serilog/Serilog.csproj
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Context/LogContextTests.cs

given in some contexts i build up a list of ILogEventEnricher of a (runtime) variable size. So the array nature of push forces a redundant array alloc.
this PR adds a `params IEnumerable` overload.
I am not sure on having the Obsolete? the OverloadResolutionPriority will point the compiler to IEnumerable overload. so it is not a compile time breaking change. and it is not a runtime breaking change. thoughts?

allow pushing a IEnumerable of ILogEventEnricher

---

Serilog.sln
src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Capturing/TrimConfiguration.cs
src/Serilog/ILLink.Substitutions.xml
src/Serilog/Serilog.csproj
src/Serilog/Serilog.props
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/AotTestApp/AotTestApp.csproj

It looks like the code has drifted a bit and disrupted the feature switch that provided AOT compatibility. I've fixed the feature switch, added the AotTestApp to the solution to ensure that it builds when the solution does, configured the AotTestApp to publish on build so that it runs the IL analysis engine, and added a Serilog.props file to the NuGet package to enable the feature switch automatically whenever trimming is enabled.
This should be much more likely to catch any regressions.
Fixes https://github.com/serilog/serilog/issues/2140

Fix AOT compatibility

---

test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Serilog.Tests.csproj

Add the targets file import to the other test projects. This should increase the test coverage to make it look closer to what a NuGet package reference would experience.

Reference targets file from tests

---

Directory.Version.props
README.md
Serilog.sln
src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Capturing/TrimConfiguration.cs
src/Serilog/Context/LogContext.cs
src/Serilog/Events/LogEvent.cs
src/Serilog/ILLink.Substitutions.xml
src/Serilog/Serilog.csproj
src/Serilog/Serilog.props
src/Serilog/Serilog.targets
src/Serilog/Settings/KeyValuePairs/SettingValueConversions.cs
test/AotTestApp/AotTestApp.csproj
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Configuration/LoggerConfigurationTests.cs
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

* #2149 - `LogEvent.AddPropertyIfAbsent(ILogEventPropertyFactory, ...)` overload that helps avoid allocations (@vanni-giachin)
* #2158 - use HTTPS in all README.md images and links (@TimHess)
* #2163 - `LogContext.Push()` overloads accepting `IEnumerable<ILogEventEnricher>` and `ReadOnlySpan<ILogEventEnricher>` (@SimonCropp)
* #2175, #2178, #2179 - fix AOT compatibility (@agocke)

4.3.0 Release

---

src/Serilog/Serilog.csproj

https://github.com/dotnet/sourcelink/releases
> Source Link is now included in .NET SDK 8 and enabled by default. Projects that migrate to .NET SDK 8 do not need to reference Source Link packages explicitly via PackageReference anymore.

remove SourceLink

---

src/Serilog/Configuration/BatchingOptions.cs
src/Serilog/Configuration/LoggerSinkConfiguration.cs

Because backpressure is not applied, instead events are discarded when the queue is full.
The xmldoc for `BatchingOptions.QueueLimit` says that backpressure is applied when the limit is exceeded.
However, in `BatchingSink.cs` we see that no backpressure is applied
```
_queue.Writer.TryWrite(logEvent);
```
Instead the event is discarded (which is good).
To me it looks like a mistake in the XMLDoc, and this PR adjusts it.

Remove backpressure from XMLDoc
