Build.ps1
Serilog.sln
src/Serilog.Extras.FSharp/Serilog.Extras.FSharp.fsproj
src/Serilog.Extras.FSharp/Serilog.Extras.FSharp.nuspec
src/Serilog.Extras.FSharp/SerilogExtrasFSharp.fs

Implements the suggestion from @vlaci in #352

Adds Serilog.Extras.FSharp

---

src/Serilog.Extras.AppSettings/Extras/AppSettings/PrefixedAppSettingsReader.cs
test/Serilog.Extras.AppSettings.Tests/PrefixedAppSettingsReaderTests.cs

#386 Expand environment variables on Extras.AppSettings values

---

src/Serilog.Sinks.ElasticSearch/LoggerConfigurationElasticSearchExtensions.cs
src/Serilog.Sinks.ElasticSearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs

Corrected spelling error in default localhost URI
Made the fact that the ES sink options are optional more obvious by making it an optional parameter

Bug es uri

---

README.md

Added a little visibility when adding viewing the repo.  This should be extended for MyGet beta builds

Added NuGet Badge

---

README.md

Updating read me to get ready for build/nuget badges for pre-release.  (v2 etc)

Changed to use branch specific badges

---

src/Serilog/Core/Pipeline/MessageTemplateCache.cs

Also changes the cache overflow policy to simply reset, hopefully keeping relevant items in the cache when it's outgrown via some misbehaving code.
Fixes #523.

Exclude large strings from the internal message template cache (fixes 523)

---

src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

Takes changes from #562 and applies to dev-v2.

Apply #562 to dev-v2

---

src/Serilog.FullNetFx/LoggerConfigurationFullNetFxExtensions.cs
src/Serilog.FullNetFx/Settings/AppSettings/AppSettingsSettings.cs
test/Serilog.Tests/Settings/AppSettingsTests.cs
test/Serilog.Tests/app.config

Add support for multiple sets of AppSettings using custom prefixes. Resolves #430

Add support for multiple sets of AppSettings using custom prefixes

---

src/Serilog/Formatting/Json/JsonFormatter-net40.cs
src/Serilog/Formatting/Json/JsonFormatter.cs

This is my proposed fix for #567. If you want me to change something, just tell me. Otherwise, :shipit:

Allow to add and override custom writers

---

README.md

[Rager.io](http://rager.io) is a service that makes it easy for developers to keep up-to-date with projects they use. When you publish a new releases of this project on NuGet, users that have signed up to receive notifications on [Rager.io](http://rager.io) will receive an email notification with a link to the new release.

Add rager releases badge to README.md

---

src/Serilog/Parameters/PropertyValueConverter.cs
src/Serilog/Policies/ReflectionTypesScalarDestructuringPolicy.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs

Allow destructuring policies to transform reflection types

---

Build.ps1
Serilog.sln
appveyor.yml
global.json
src/Serilog/Context/ImmutableStack.cs
src/Serilog/Context/LogContext.cs
src/Serilog/Core/Logger.cs
src/Serilog/Core/Pipeline/SilentLogger.cs
src/Serilog/Serilog.xproj
src/Serilog/project.json
test/Serilog.Tests/Context/LogContextTests.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Core/SafeAggregateSinkTests.cs
test/Serilog.Tests/Events/LogEventPropertyValueTests.cs
test/Serilog.Tests/LogTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs
test/Serilog.Tests/Parameters/PropertyValueConverterTests.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/Serilog.Tests/Support/StringSink.cs
test/Serilog.Tests/project.json
test/TestDummies/DummyLoggerConfigurationExtensions.cs
test/TestDummies/DummyThreadIdEnricher.cs
test/TestDummies/Properties/AssemblyInfo.cs
test/TestDummies/TestDummies.xproj
test/TestDummies/project.json

Work still required on _Build.ps1_

Code/test port to .NET Core RC2

---

appveyor.yml

To fix build issues created re: change in dotnet/cli [commit](https://github.com/dotnet/cli/commit/78a70f049a3074bceb7f4106ceab7f420c217531)

Corrected script path to match new structure in dotnet/cli

---

build.sh

Updated the existing `build.sh` to work with dotnet core.

Bash script for dotnet core.

---

.travis.yml
README.md
build.sh

Replaces #757
* Travis build 
* Reverted to loop in build.sh.
Details at https://travis-ci.org/serilog/serilog
Possibly look at using http://shields.io/ for badges in the future.

New Travis Build

---

build.sh

What the title says 😝 // @merbla

Don't run build twice

---

src/Serilog/Configuration/LoggerMinimumLevelConfiguration.cs
src/Serilog/Core/LevelOverrideMap.cs
src/Serilog/Core/Logger.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.Tests/Core/LevelOverrideMapTests.cs
test/Serilog.Tests/LoggerConfigurationTests.cs

#754 
```csharp
var logger = new LoggerConfiguration()
.MinimumLevel.Debug()
.MinimumLevel.Override("Microsoft", LogEventLevel.Error)
//
```

MinimumLevel.Override()

---

appveyor.yml

Add tagging/GitHub releases support to build via AppVeyor

---

Serilog.sln.DotSettings

Add resharper auto-added setting

---

.travis.yml
appveyor.yml
global.json
src/Serilog/project.json
test/Serilog.PerformanceTests/project.json
test/Serilog.Tests/project.json
test/TestDummies/project.json

Warning this PR is set to merge into staging-2.0

dotnet cli preview2 and core RTM

---

src/Serilog/Configuration/LoggerDestructuringConfiguration.cs

Provide `ByTransformingWhere` for more complex transformations

---

appveyor.yml
src/Serilog/Parameters/PropertyBinder.cs
test/Serilog.Tests/Core/LogEventPropertyCapturingTests.cs

See #741 for details.
This addresses #737

Capture additional params (named) not in template

---

Build.ps1
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs
test/TestDummies/DummyLoggerConfigurationExtensions.cs

Select configuration methods based on matched parameter count

---

src/Serilog/Configuration/LoggerAuditSinkConfiguration.cs
src/Serilog/project.json

Release 2.2.1

---

src/Serilog/Parameters/PropertyValueConverter.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs

This commit should fix issue #852.
PS.: I've done this on a Mac, so I hope that the CI will test others OS...

Fix for issue #852

---

appveyor.yml

[Codecov.io](https://Codecov.io) is a free (for FOSS) Code coverage platform in the cloud. You can sign up with your GitHub account and add in the future badges and webhooks. 
This PR will submit the code coverage to Codecov.io

Added codecov.io integration

---

src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs

An attempt to resolve https://github.com/serilog/serilog-settings-appsettings/issues/2
Have implemented what I understand to be the main issue described there. Let me know if there is more to be done.

Allow overriding log level via config files

---

src/Serilog/Parsing/MessageTemplateParser.cs
test/Serilog.Tests/Parsing/MessageTemplateParserTests.cs

Parsing longer property tokens with zero-length names

---

test/Serilog.PerformanceTests/Harness.cs
test/Serilog.PerformanceTests/MessageTemplateRenderingBenchmark.cs
test/Serilog.PerformanceTests/OutputTemplateRenderingBenchmark.cs
test/Serilog.PerformanceTests/Support/Some.cs

Still tweaking this, but will support the work in #958

Output template formatting harness

---

build.sh

* Removed install from build script and rely on Travis yml

Tooling Cleanup - Rely on Travis.yml for Build requirements

---

appveyor-perftest.yml

Looking to setup an AppVeyor Build for Perf Tests here - https://ci.appveyor.com/project/serilog/serilog-jaske

Independent Build for Perf Tests.

---

.travis.yml

* As per https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

Travis CI Image - use edge group 

---

src/Serilog/Context/LogContext.cs
test/Serilog.Tests/Context/LogContextTests.cs

fixes [#987](https://github.com/serilog/serilog/issues/987)

LogContext's remoting issue fix for .NET 4.5

---

src/Serilog/Context/LogContext.cs
test/Serilog.Tests/Context/LogContextTests.cs

This PR is implementation of #1006 
Add Suspend and Reset methods to LogContext to allow removing enrichers. 
Add tests for Suspend and Reset methods.

Implementation of #1006 

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

* Code of Conduct
* Contributing Guide
* Issue Template from #842 
* PR template for #842
Code of Conduct notes the following references:
* https://www.contributor-covenant.org/
* https://www.contributor-covenant.org/version/1/4/code_of_conduct.md

Code of Conduct, Contributing Guide & templates for issues and PRs

---

src/Serilog/Context/LogContext.cs

Fix the last ReSharper warning that was left after #1042 according to discussion https://github.com/serilog/serilog/pull/1042#issuecomment-337764490

Fix last ReSharper warning

---

.travis.yml
build.sh

**Details**
* Target `netcoreapp2` for nix script
* Ensure exit on error in `build.sh`
* #1136 
* No

Fix OSX/*nix build #1136

---

Build.ps1
Directory.Build.props
Serilog.sln
test/Serilog.Tests/Serilog.Tests.csproj

Added SourceLink support for a better debugging experience in VS / VS Code:
https://github.com/ctaggart/SourceLink
Partially fixes [#1126](https://github.com/serilog/serilog/issues/1126)
No.

SourceLink v2 support added

---

src/Serilog/Serilog.csproj

fixing repository url

---

src/Serilog/Capturing/GetablePropertyFinder.cs
test/Serilog.Tests/Capturing/GetablePropertyFinderTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

Fix on GetPropertiesRecursive method not to generate exception on the… 

---

src/Serilog/Serilog.csproj

Add .NET Standard 2.0 target

---

src/Serilog/Context/ImmutableStack.cs

Hi!
There are some allocations during an [enumeration](https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs#L196) of `ImmutableStack`:
The PR fixes them by introducing handwritten enumerator which is `struct` and most of the time will live on the stack and will not be boxed.
Nope

Handwritten implementation of IEnumerator to avoid allocations

---

src/Serilog/Capturing/PropertyBinder.cs
src/Serilog/Core/Logger.cs
src/Serilog/Core/Sinks/SecondaryLoggerSink.cs
src/Serilog/Filters/Matching.cs
src/Serilog/Formatting/Display/MessageTemplateTextFormatter.cs
src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/Parsing/MessageTemplateParser.cs
src/Serilog/Parsing/PropertyToken.cs
src/Serilog/Rendering/MessageTemplateRenderer.cs
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.PerformanceTests/BindingBenchmark.cs
test/Serilog.PerformanceTests/Support/ConcurrentDictionaryTemplateCache.cs
test/Serilog.Tests/Core/LevelOverrideMapTests.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs

seem to be consistent with the majority of the coding style

use var for out

---

src/Serilog/Serilog.csproj

remove unnecessary System.Collections.NonGeneric dependency for netstandard2.0
fix #1341

remove unnecessary System.Collections.NonGeneric dependency for netstandard2.0

---

INFLUENCES.md

Acknowledge the major sources of ideas and inspiration.
Resolves #1347

INFLUENCES.md

---

src/Serilog/Core/Logger.cs

Documentation clarification.

---

README.md

#1376 
No.
Markdown file only change.

Fixing up for grabs link.

---

Build.ps1
appveyor.yml
build.sh
global.json
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Serilog.Tests.csproj

Just some housekeeping; looking into why the build's showing up as broken :-)

.NET 5.0.202 SDK, main branch change

---

src/Serilog/Capturing/PropertyValueConverter.cs

Fixed issue

---

src/Serilog/ILogger.cs

- Update ILogger examples XML documentation to use `<code>`
- Fix an errant `>`

Update ILogger XML documentation

---

Serilog.sln.DotSettings
src/Serilog/Core/Logger.cs
src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/ILogger.cs
src/Serilog/Log.cs

Spotted one small issue reviewing #1614.

Fix nullable annotation on Log.ForContext(); minor nullability tweaks

---

src/Serilog/Log.cs

This should bring `Log` into line with `ILogger`.

More nullable annotation updates

---

src/Serilog/Core/Logger.cs
src/Serilog/ILogger.cs

Reverts serilog/serilog#1689
These should have targeted `dev`

Revert "Remove ! operator from nulls in conditions"

---

.gitattributes
.gitignore
Serilog.sln
test/Serilog.ApprovalTests/ApiApprovalTests.cs
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.ApprovalTests/Serilog.approved.txt

Helps to verify changes in public API in incoming PRs.

Add API approval test

---

src/Serilog/Events/DictionaryValue.cs
src/Serilog/Events/ScalarValue.cs
src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/Formatting/Raw/RawFormatter.cs

better perf options for the underlying writer when it knows it is a single char

use WriteLine char

---

src/Serilog/Context/LogContext.cs
src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj

all targets now support AsyncLocal

remove FEATURE_ASYNCLOCAL

---

src/Serilog/Core/Pipeline/MessageTemplateCache.cs
src/Serilog/Serilog.csproj

remove FEATURE_HASHTABLE

---

src/Serilog/Core/Pipeline/MessageTemplateCache.cs

Co-Authored-By: Sergey Komisarchik <15090984+skomis-mm@users.noreply.github.com>

comments on Hashtable in MessageTemplateCache

---

src/Serilog/Capturing/PropertyValueConverter.cs

avoid repeated GetType in PropertyValueConverter

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Serilog.csproj
test/Serilog.Tests/Serilog.Tests.csproj
test/TestDummies/TestDummies.csproj

Move net46 to net461

---

src/Serilog/Core/Logger.cs

... when using GetEffectiveLevel

no point putting _minimumLevel and _levelSwitch on stack

---

src/Serilog/Core/Logger.cs
src/Serilog/Core/Sinks/RestrictedSink.cs
src/Serilog/Formatting/Display/LevelOutputFormat.cs

in most cases we can continue to use the strong typed enums

avoid casting enum to int where possible

---

test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Serilog.Tests.csproj

all our TFMs support GETCURRENTMETHOD

remove FEATURE_GETCURRENTMETHOD const

---

test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/TestDummies/TestDummies.csproj

missing PolySharp changes

---

Serilog.sln
src/Serilog/Configuration/LoggerEnrichmentConfiguration.cs
src/Serilog/Context/LogContext.cs
src/Serilog/Core/ILogEventFilter.cs
src/Serilog/Core/ILogEventPropertyFactory.cs
src/Serilog/Core/ILogEventPropertyValueFactory.cs
src/Serilog/Core/Logger.cs
src/Serilog/Events/LogEventProperty.cs
src/Serilog/Events/ScalarValue.cs
src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/ILogger.cs
src/Serilog/Log.cs
src/Serilog/LoggerExtensions.cs
src/Serilog/Parsing/PropertyToken.cs
src/Serilog/Parsing/TextToken.cs

Use langword in xml comments

---

src/Serilog/Capturing/PropertyValueConverter.cs
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs

Destructure ReadOnlyDictionary as Dictionary

---

src/Serilog/Core/LoggingLevelSwitch.cs
src/Serilog/Core/LoggingLevelSwitchChangedEventArgs.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Core/LoggingLevekSwitchTests.cs

Add LoggingLevelSwitch.MinimumLevelChanged

---

src/Serilog/Capturing/PropertyValueConverter.cs
src/Serilog/Configuration/LoggerDestructuringConfiguration.cs
src/Serilog/LoggerConfiguration.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Core/LogEventPropertyCapturingTests.cs
test/Serilog.Tests/Core/MessageTemplateTests.cs
test/Serilog.Tests/Events/LogEventPropertyValueTests.cs
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs
test/Serilog.Tests/Support/DelegatingSink.cs

Add Destructure.AsDictionary<T>()

---

README.md

See https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges

Serve README.md logo from raw.github.com so that it will be displayed on NuGet.org

---

src/Serilog/Formatting/Json/JsonFormatter.cs
src/Serilog/Serilog.csproj
test/Serilog.Tests/Formatting/Json/JsonFormatterTests.cs

* #1926 - fix `JsonFormatter` output for `renderMessage = true` (@nblumhardt)

3.0.1 Release

---

README.md

I don't think there are many people upgrading from 1.x to 2.0 these days 😅

Update upgrading instructions in README.md

---

global.json
src/Serilog/Properties/AssemblyInfo.cs
src/Serilog/Serilog.csproj
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.Tests/Serilog.Tests.csproj

Set dev branch version to `4.0.0-*`, unpin `[AssemblyVersion]`

---

Directory.Build.props
src/Serilog/Serilog.csproj
src/Serilog/Settings/KeyValuePairs/KeyValuePairSettings.cs
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Serilog.Tests.csproj

Aiming for the scheme discussed in #1970; depends on #2015.

Update TFMs for Serilog 4.0

---

.editorconfig
src/Serilog/Events/LogEvent.cs
test/Serilog.ApprovalTests/ApiApprovalTests.cs
test/Serilog.ApprovalTests/Serilog.approved.txt
test/Serilog.Tests/Events/LogEventTests.cs
test/Serilog.Tests/Support/Some.cs

Add `LogEvent.UnstableAssembleFromParts()`

---

src/Serilog/Serilog.csproj
test/Serilog.ApprovalTests/Serilog.ApprovalTests.csproj
test/Serilog.PerformanceTests/Serilog.PerformanceTests.csproj
test/Serilog.Tests/Capturing/PropertyValueConverterTests.cs
test/Serilog.Tests/Formatting/Json/JsonValueFormatterTests.cs
test/Serilog.Tests/MethodOverloadConventionTests.cs
test/Serilog.Tests/Rendering/MessageTemplateRendererTests.cs
test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Settings/SettingValueConversionsTests.cs
test/TestDummies/TestDummies.csproj

Don't think there should be any observable breakage with this one.

Update all dependencies, fix new xUnit lints

---

test/Serilog.Tests/Core/BatchingSinkTests.cs

(CI is getting flaky, seems like task dispatch or thread spin-up time is too slow.)

Attempt to make tests more robust on slow CI machines by increasing time steps

---

src/Serilog/Capturing/PropertyValueConverter.cs
test/Serilog.Tests/Core/LoggerTests.cs
test/Serilog.Tests/Serilog.Tests.csproj
test/Serilog.Tests/Support/Extensions.cs

fixes https://github.com/serilog/serilog/issues/2019
developed based on https://github.com/serilog/serilog/pull/2035
To support multi dimensional arrays

Extend Support for Multi-Dimensional Arrays

---

src/Serilog/Serilog.csproj
src/Serilog/Serilog.targets
test/AotTestApp/AotTestApp.csproj

I believe this fixes the problem observed in https://github.com/serilog/serilog/pull/2175.
I tried to validate this locally, but I'm not sure how thorough I am. I'd appreciate instructions on how to run the test suite.

Move trim option to targets file
